#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 182
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 3
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 13

enum {
  sym_assignment_operator = 1,
  aux_sym__inline_value_token1 = 2,
  aux_sym__multiline_empty_token1 = 3,
  aux_sym__inline_empty_token1 = 4,
  aux_sym__integer_token1 = 5,
  aux_sym__signed_integer_token1 = 6,
  aux_sym__signed_integer_token2 = 7,
  anon_sym_DOT = 8,
  aux_sym__inline_text_token1 = 9,
  sym__name_ = 10,
  sym__indent_ = 11,
  sym__dedent_ = 12,
  sym__samedent_ = 13,
  sym__newline_ = 14,
  sym__line_ending_ = 15,
  sym__end_of_file_ = 16,
  sym__multiline_spacing_ = 17,
  sym__inline_spacing_ = 18,
  sym__error_ = 19,
  sym_src = 20,
  sym__current_indent = 21,
  sym__increase_indent = 22,
  sym__line_ending = 23,
  sym__end_of_file = 24,
  sym__struct = 25,
  sym_map = 26,
  sym__multiline_map = 27,
  sym__multiline_map_entry = 28,
  sym__multiline_map_named_entry = 29,
  sym_name = 30,
  sym__inline_value = 31,
  sym__child_value = 32,
  sym__multiline_literal = 33,
  sym__inline_literal = 34,
  sym__multiline_empty = 35,
  sym__inline_empty = 36,
  sym__inline_number = 37,
  sym__signed_number = 38,
  sym__unsigned_number = 39,
  sym__integer = 40,
  sym__signed_integer = 41,
  sym__decimal = 42,
  sym__signed_decimal = 43,
  sym__inline_text = 44,
  aux_sym_src_repeat1 = 45,
  aux_sym__multiline_map_repeat1 = 46,
  alias_sym_HIDDEN_multiline_map = 47,
  alias_sym_HIDDEN_signed_decimal = 48,
  alias_sym_empty = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_assignment_operator] = "HIDDEN_multiline_map_named_entry",
  [aux_sym__inline_value_token1] = "HIDDEN_inline_value",
  [aux_sym__multiline_empty_token1] = "empty_ALIAS_OF_multiline_empty",
  [aux_sym__inline_empty_token1] = "empty_ALIAS_OF_inline_empty",
  [aux_sym__integer_token1] = "integer_ALIAS_OF_integer",
  [aux_sym__signed_integer_token1] = "integer_ALIAS_OF_signed_integer",
  [aux_sym__signed_integer_token2] = "integer_ALIAS_OF_signed_integer",
  [anon_sym_DOT] = "HIDDEN_decimal",
  [aux_sym__inline_text_token1] = "text_ALIAS_OF_inline_text",
  [sym__name_] = "_name_",
  [sym__indent_] = "HIDDEN_increase_indent",
  [sym__dedent_] = "HIDDEN_decrease_indent",
  [sym__samedent_] = "HIDDEN_current_indent",
  [sym__newline_] = "HIDDEN_newline",
  [sym__line_ending_] = "HIDDEN_line_ending",
  [sym__end_of_file_] = "HIDDEN_end_of_file",
  [sym__multiline_spacing_] = "HIDDEN_multiline_spacing",
  [sym__inline_spacing_] = "_inline_spacing_",
  [sym__error_] = "_error_",
  [sym_src] = "src",
  [sym__current_indent] = "_current_indent",
  [sym__increase_indent] = "HIDDEN_child_value",
  [sym__line_ending] = "_line_ending",
  [sym__end_of_file] = "_end_of_file",
  [sym__struct] = "_struct",
  [sym_map] = "HIDDEN_struct",
  [sym__multiline_map] = "_multiline_map",
  [sym__multiline_map_entry] = "_multiline_map_entry",
  [sym__multiline_map_named_entry] = "named_entry_ALIAS_OF_multiline_map_entry",
  [sym_name] = "HIDDEN_multiline_map_named_entry",
  [sym__inline_value] = "HIDDEN_multiline_map_named_entry",
  [sym__child_value] = "HIDDEN_multiline_map_named_entry",
  [sym__multiline_literal] = "_multiline_literal",
  [sym__inline_literal] = "_inline_literal",
  [sym__multiline_empty] = "literal_ALIAS_OF_multiline_literal",
  [sym__inline_empty] = "literal_ALIAS_OF_inline_literal",
  [sym__inline_number] = "literal_ALIAS_OF_inline_literal",
  [sym__signed_number] = "number_ALIAS_OF_inline_number",
  [sym__unsigned_number] = "number_ALIAS_OF_inline_number",
  [sym__integer] = "HIDDEN_decimal",
  [sym__signed_integer] = "HIDDEN_signed_number",
  [sym__decimal] = "HIDDEN_unsigned_number",
  [sym__signed_decimal] = "HIDDEN_signed_number",
  [sym__inline_text] = "literal_ALIAS_OF_inline_literal",
  [aux_sym_src_repeat1] = "src_repeat1",
  [aux_sym__multiline_map_repeat1] = "_multiline_map_repeat1",
  [alias_sym_HIDDEN_multiline_map] = "HIDDEN_multiline_map",
  [alias_sym_HIDDEN_signed_decimal] = "HIDDEN_signed_decimal",
  [alias_sym_empty] = "empty",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_assignment_operator] = sym_assignment_operator,
  [aux_sym__inline_value_token1] = aux_sym__inline_value_token1,
  [aux_sym__multiline_empty_token1] = aux_sym__multiline_empty_token1,
  [aux_sym__inline_empty_token1] = aux_sym__inline_empty_token1,
  [aux_sym__integer_token1] = aux_sym__integer_token1,
  [aux_sym__signed_integer_token1] = aux_sym__signed_integer_token1,
  [aux_sym__signed_integer_token2] = aux_sym__signed_integer_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym__inline_text_token1] = aux_sym__inline_text_token1,
  [sym__name_] = sym__name_,
  [sym__indent_] = sym__indent_,
  [sym__dedent_] = sym__dedent_,
  [sym__samedent_] = sym__samedent_,
  [sym__newline_] = sym__newline_,
  [sym__line_ending_] = sym__line_ending_,
  [sym__end_of_file_] = sym__end_of_file_,
  [sym__multiline_spacing_] = sym__multiline_spacing_,
  [sym__inline_spacing_] = sym__inline_spacing_,
  [sym__error_] = sym__error_,
  [sym_src] = sym_src,
  [sym__current_indent] = sym__current_indent,
  [sym__increase_indent] = sym__increase_indent,
  [sym__line_ending] = sym__line_ending,
  [sym__end_of_file] = sym__end_of_file,
  [sym__struct] = sym__struct,
  [sym_map] = sym_map,
  [sym__multiline_map] = sym__multiline_map,
  [sym__multiline_map_entry] = sym__multiline_map_entry,
  [sym__multiline_map_named_entry] = sym__multiline_map_named_entry,
  [sym_name] = sym_assignment_operator,
  [sym__inline_value] = sym_assignment_operator,
  [sym__child_value] = sym_assignment_operator,
  [sym__multiline_literal] = sym__multiline_literal,
  [sym__inline_literal] = sym__inline_literal,
  [sym__multiline_empty] = sym__multiline_empty,
  [sym__inline_empty] = sym__inline_empty,
  [sym__inline_number] = sym__inline_empty,
  [sym__signed_number] = sym__signed_number,
  [sym__unsigned_number] = sym__signed_number,
  [sym__integer] = anon_sym_DOT,
  [sym__signed_integer] = sym__signed_integer,
  [sym__decimal] = sym__decimal,
  [sym__signed_decimal] = sym__signed_integer,
  [sym__inline_text] = sym__inline_empty,
  [aux_sym_src_repeat1] = aux_sym_src_repeat1,
  [aux_sym__multiline_map_repeat1] = aux_sym__multiline_map_repeat1,
  [alias_sym_HIDDEN_multiline_map] = alias_sym_HIDDEN_multiline_map,
  [alias_sym_HIDDEN_signed_decimal] = alias_sym_HIDDEN_signed_decimal,
  [alias_sym_empty] = alias_sym_empty,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline_value_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__multiline_empty_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline_empty_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__integer_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__signed_integer_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__signed_integer_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline_text_token1] = {
    .visible = true,
    .named = true,
  },
  [sym__name_] = {
    .visible = false,
    .named = true,
  },
  [sym__indent_] = {
    .visible = true,
    .named = true,
  },
  [sym__dedent_] = {
    .visible = true,
    .named = true,
  },
  [sym__samedent_] = {
    .visible = true,
    .named = true,
  },
  [sym__newline_] = {
    .visible = true,
    .named = true,
  },
  [sym__line_ending_] = {
    .visible = true,
    .named = true,
  },
  [sym__end_of_file_] = {
    .visible = true,
    .named = true,
  },
  [sym__multiline_spacing_] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_spacing_] = {
    .visible = false,
    .named = true,
  },
  [sym__error_] = {
    .visible = false,
    .named = true,
  },
  [sym_src] = {
    .visible = true,
    .named = true,
  },
  [sym__current_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__increase_indent] = {
    .visible = true,
    .named = true,
  },
  [sym__line_ending] = {
    .visible = false,
    .named = true,
  },
  [sym__end_of_file] = {
    .visible = false,
    .named = true,
  },
  [sym__struct] = {
    .visible = false,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym__multiline_map] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_map_entry] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_map_named_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_value] = {
    .visible = true,
    .named = true,
  },
  [sym__child_value] = {
    .visible = true,
    .named = true,
  },
  [sym__multiline_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_empty] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_empty] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_number] = {
    .visible = true,
    .named = true,
  },
  [sym__signed_number] = {
    .visible = true,
    .named = true,
  },
  [sym__unsigned_number] = {
    .visible = true,
    .named = true,
  },
  [sym__integer] = {
    .visible = true,
    .named = true,
  },
  [sym__signed_integer] = {
    .visible = true,
    .named = true,
  },
  [sym__decimal] = {
    .visible = true,
    .named = true,
  },
  [sym__signed_decimal] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_src_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__multiline_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_HIDDEN_multiline_map] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_HIDDEN_signed_decimal] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_empty] = {
    .visible = true,
    .named = true,
  },
};

enum {
  field_key = 1,
  field_operator = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_operator] = "operator",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [3] = {.index = 0, .length = 3},
  [8] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0, .inherited = true},
    {field_operator, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [3] =
    {field_key, 0},
    {field_operator, 1},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_empty,
  },
  [2] = {
    [0] = alias_sym_HIDDEN_multiline_map,
  },
  [4] = {
    [0] = sym__decimal,
  },
  [5] = {
    [0] = alias_sym_HIDDEN_multiline_map,
    [1] = alias_sym_HIDDEN_multiline_map,
  },
  [6] = {
    [1] = alias_sym_empty,
  },
  [7] = {
    [0] = alias_sym_HIDDEN_multiline_map,
    [1] = alias_sym_HIDDEN_multiline_map,
    [2] = alias_sym_HIDDEN_multiline_map,
  },
  [9] = {
    [0] = alias_sym_HIDDEN_signed_decimal,
    [1] = alias_sym_HIDDEN_signed_decimal,
    [2] = alias_sym_HIDDEN_signed_decimal,
  },
  [10] = {
    [0] = alias_sym_HIDDEN_multiline_map,
    [1] = alias_sym_HIDDEN_multiline_map,
    [2] = alias_sym_HIDDEN_multiline_map,
    [3] = alias_sym_HIDDEN_multiline_map,
  },
  [11] = {
    [1] = aux_sym__inline_value_token1,
    [2] = aux_sym__inline_value_token1,
  },
  [12] = {
    [0] = sym__increase_indent,
    [2] = sym__increase_indent,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__line_ending, 4,
    sym__line_ending,
    alias_sym_HIDDEN_multiline_map,
    aux_sym__inline_value_token1,
    sym__increase_indent,
  sym__end_of_file, 3,
    sym__end_of_file,
    alias_sym_HIDDEN_multiline_map,
    alias_sym_empty,
  sym_map, 2,
    sym_map,
    sym__increase_indent,
  sym__multiline_map_entry, 2,
    sym__multiline_map_entry,
    alias_sym_HIDDEN_multiline_map,
  sym__multiline_literal, 2,
    sym__multiline_literal,
    sym__increase_indent,
  sym__inline_literal, 3,
    sym__inline_literal,
    aux_sym__inline_value_token1,
    sym__increase_indent,
  sym__integer, 3,
    anon_sym_DOT,
    alias_sym_HIDDEN_signed_decimal,
    sym__decimal,
  sym__signed_integer, 2,
    sym__signed_integer,
    alias_sym_HIDDEN_signed_decimal,
  aux_sym__multiline_map_repeat1, 2,
    aux_sym__multiline_map_repeat1,
    alias_sym_HIDDEN_multiline_map,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 3,
  [6] = 6,
  [7] = 6,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 12,
  [16] = 10,
  [17] = 12,
  [18] = 18,
  [19] = 10,
  [20] = 18,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 32,
  [34] = 9,
  [35] = 35,
  [36] = 32,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 35,
  [42] = 42,
  [43] = 30,
  [44] = 44,
  [45] = 35,
  [46] = 37,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 30,
  [54] = 37,
  [55] = 31,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 14,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 31,
  [66] = 50,
  [67] = 63,
  [68] = 14,
  [69] = 40,
  [70] = 61,
  [71] = 51,
  [72] = 52,
  [73] = 62,
  [74] = 64,
  [75] = 60,
  [76] = 58,
  [77] = 57,
  [78] = 56,
  [79] = 51,
  [80] = 52,
  [81] = 39,
  [82] = 48,
  [83] = 40,
  [84] = 42,
  [85] = 47,
  [86] = 49,
  [87] = 44,
  [88] = 48,
  [89] = 50,
  [90] = 14,
  [91] = 44,
  [92] = 49,
  [93] = 39,
  [94] = 64,
  [95] = 62,
  [96] = 38,
  [97] = 60,
  [98] = 63,
  [99] = 61,
  [100] = 58,
  [101] = 35,
  [102] = 37,
  [103] = 103,
  [104] = 103,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 105,
  [109] = 106,
  [110] = 107,
  [111] = 111,
  [112] = 112,
  [113] = 106,
  [114] = 114,
  [115] = 105,
  [116] = 112,
  [117] = 114,
  [118] = 111,
  [119] = 106,
  [120] = 111,
  [121] = 112,
  [122] = 35,
  [123] = 112,
  [124] = 31,
  [125] = 111,
  [126] = 105,
  [127] = 103,
  [128] = 30,
  [129] = 107,
  [130] = 31,
  [131] = 37,
  [132] = 30,
  [133] = 112,
  [134] = 111,
  [135] = 52,
  [136] = 62,
  [137] = 44,
  [138] = 39,
  [139] = 64,
  [140] = 48,
  [141] = 50,
  [142] = 38,
  [143] = 63,
  [144] = 14,
  [145] = 61,
  [146] = 52,
  [147] = 147,
  [148] = 148,
  [149] = 39,
  [150] = 150,
  [151] = 64,
  [152] = 49,
  [153] = 153,
  [154] = 154,
  [155] = 44,
  [156] = 63,
  [157] = 61,
  [158] = 49,
  [159] = 14,
  [160] = 14,
  [161] = 161,
  [162] = 51,
  [163] = 47,
  [164] = 40,
  [165] = 165,
  [166] = 48,
  [167] = 50,
  [168] = 161,
  [169] = 169,
  [170] = 170,
  [171] = 171,
  [172] = 57,
  [173] = 58,
  [174] = 161,
  [175] = 161,
  [176] = 171,
  [177] = 177,
  [178] = 60,
  [179] = 171,
  [180] = 161,
  [181] = 56,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (eof) ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(8);
      END_STATE();
    case 1:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 2:
      if (eof) ADVANCE(4);
      if (lookahead == '-') ADVANCE(1);
      if (lookahead == '.') ADVANCE(16);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(3)
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(3)
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym_assignment_operator);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym__inline_value_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '-') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(8);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(10);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__inline_empty_token1);
      if (lookahead == '-') ADVANCE(14);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym__inline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym__signed_integer_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__signed_integer_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym__inline_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 7, .external_lex_state = 2},
  [2] = {.lex_state = 7, .external_lex_state = 2},
  [3] = {.lex_state = 7, .external_lex_state = 3},
  [4] = {.lex_state = 7, .external_lex_state = 3},
  [5] = {.lex_state = 7, .external_lex_state = 3},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 7, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 7, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 4},
  [16] = {.lex_state = 0, .external_lex_state = 4},
  [17] = {.lex_state = 0, .external_lex_state = 4},
  [18] = {.lex_state = 0, .external_lex_state = 2},
  [19] = {.lex_state = 0, .external_lex_state = 4},
  [20] = {.lex_state = 0, .external_lex_state = 4},
  [21] = {.lex_state = 0, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 5},
  [23] = {.lex_state = 7, .external_lex_state = 3},
  [24] = {.lex_state = 0, .external_lex_state = 5},
  [25] = {.lex_state = 0, .external_lex_state = 5},
  [26] = {.lex_state = 0, .external_lex_state = 5},
  [27] = {.lex_state = 0, .external_lex_state = 5},
  [28] = {.lex_state = 0, .external_lex_state = 5},
  [29] = {.lex_state = 0, .external_lex_state = 5},
  [30] = {.lex_state = 2, .external_lex_state = 2},
  [31] = {.lex_state = 2, .external_lex_state = 2},
  [32] = {.lex_state = 2, .external_lex_state = 6},
  [33] = {.lex_state = 2, .external_lex_state = 6},
  [34] = {.lex_state = 0, .external_lex_state = 5},
  [35] = {.lex_state = 2, .external_lex_state = 2},
  [36] = {.lex_state = 2, .external_lex_state = 6},
  [37] = {.lex_state = 2, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 2, .external_lex_state = 4},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 2, .external_lex_state = 4},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 2, .external_lex_state = 5},
  [46] = {.lex_state = 2, .external_lex_state = 4},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 0, .external_lex_state = 2},
  [53] = {.lex_state = 2, .external_lex_state = 5},
  [54] = {.lex_state = 2, .external_lex_state = 5},
  [55] = {.lex_state = 2, .external_lex_state = 4},
  [56] = {.lex_state = 0, .external_lex_state = 2},
  [57] = {.lex_state = 0, .external_lex_state = 2},
  [58] = {.lex_state = 0, .external_lex_state = 2},
  [59] = {.lex_state = 0, .external_lex_state = 2},
  [60] = {.lex_state = 0, .external_lex_state = 2},
  [61] = {.lex_state = 0, .external_lex_state = 2},
  [62] = {.lex_state = 0, .external_lex_state = 2},
  [63] = {.lex_state = 0, .external_lex_state = 2},
  [64] = {.lex_state = 0, .external_lex_state = 2},
  [65] = {.lex_state = 2, .external_lex_state = 5},
  [66] = {.lex_state = 0, .external_lex_state = 5},
  [67] = {.lex_state = 0, .external_lex_state = 4},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 0, .external_lex_state = 4},
  [70] = {.lex_state = 0, .external_lex_state = 4},
  [71] = {.lex_state = 0, .external_lex_state = 5},
  [72] = {.lex_state = 0, .external_lex_state = 4},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 4},
  [75] = {.lex_state = 0, .external_lex_state = 4},
  [76] = {.lex_state = 0, .external_lex_state = 4},
  [77] = {.lex_state = 0, .external_lex_state = 4},
  [78] = {.lex_state = 0, .external_lex_state = 4},
  [79] = {.lex_state = 0, .external_lex_state = 4},
  [80] = {.lex_state = 0, .external_lex_state = 5},
  [81] = {.lex_state = 0, .external_lex_state = 4},
  [82] = {.lex_state = 0, .external_lex_state = 5},
  [83] = {.lex_state = 0, .external_lex_state = 5},
  [84] = {.lex_state = 0, .external_lex_state = 4},
  [85] = {.lex_state = 0, .external_lex_state = 4},
  [86] = {.lex_state = 0, .external_lex_state = 4},
  [87] = {.lex_state = 0, .external_lex_state = 4},
  [88] = {.lex_state = 0, .external_lex_state = 4},
  [89] = {.lex_state = 0, .external_lex_state = 4},
  [90] = {.lex_state = 0, .external_lex_state = 4},
  [91] = {.lex_state = 0, .external_lex_state = 5},
  [92] = {.lex_state = 0, .external_lex_state = 5},
  [93] = {.lex_state = 0, .external_lex_state = 5},
  [94] = {.lex_state = 0, .external_lex_state = 5},
  [95] = {.lex_state = 0, .external_lex_state = 5},
  [96] = {.lex_state = 0, .external_lex_state = 4},
  [97] = {.lex_state = 0, .external_lex_state = 5},
  [98] = {.lex_state = 0, .external_lex_state = 5},
  [99] = {.lex_state = 0, .external_lex_state = 5},
  [100] = {.lex_state = 0, .external_lex_state = 5},
  [101] = {.lex_state = 2, .external_lex_state = 7},
  [102] = {.lex_state = 2, .external_lex_state = 6},
  [103] = {.lex_state = 0, .external_lex_state = 8},
  [104] = {.lex_state = 0, .external_lex_state = 8},
  [105] = {.lex_state = 0, .external_lex_state = 9},
  [106] = {.lex_state = 0, .external_lex_state = 9},
  [107] = {.lex_state = 0, .external_lex_state = 6},
  [108] = {.lex_state = 0, .external_lex_state = 9},
  [109] = {.lex_state = 0, .external_lex_state = 9},
  [110] = {.lex_state = 0, .external_lex_state = 6},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0, .external_lex_state = 9},
  [114] = {.lex_state = 0, .external_lex_state = 7},
  [115] = {.lex_state = 0, .external_lex_state = 9},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0, .external_lex_state = 7},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0, .external_lex_state = 9},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 2, .external_lex_state = 6},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 2, .external_lex_state = 7},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0, .external_lex_state = 9},
  [127] = {.lex_state = 0, .external_lex_state = 8},
  [128] = {.lex_state = 2, .external_lex_state = 6},
  [129] = {.lex_state = 0, .external_lex_state = 6},
  [130] = {.lex_state = 2, .external_lex_state = 6},
  [131] = {.lex_state = 2, .external_lex_state = 7},
  [132] = {.lex_state = 2, .external_lex_state = 7},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0, .external_lex_state = 7},
  [136] = {.lex_state = 0, .external_lex_state = 7},
  [137] = {.lex_state = 0, .external_lex_state = 7},
  [138] = {.lex_state = 0, .external_lex_state = 6},
  [139] = {.lex_state = 0, .external_lex_state = 6},
  [140] = {.lex_state = 0, .external_lex_state = 7},
  [141] = {.lex_state = 0, .external_lex_state = 7},
  [142] = {.lex_state = 0, .external_lex_state = 7},
  [143] = {.lex_state = 0, .external_lex_state = 6},
  [144] = {.lex_state = 0, .external_lex_state = 9},
  [145] = {.lex_state = 0, .external_lex_state = 6},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0, .external_lex_state = 7},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0, .external_lex_state = 7},
  [152] = {.lex_state = 0, .external_lex_state = 6},
  [153] = {.lex_state = 0},
  [154] = {.lex_state = 0},
  [155] = {.lex_state = 0, .external_lex_state = 6},
  [156] = {.lex_state = 0, .external_lex_state = 7},
  [157] = {.lex_state = 0, .external_lex_state = 7},
  [158] = {.lex_state = 0, .external_lex_state = 7},
  [159] = {.lex_state = 0, .external_lex_state = 7},
  [160] = {.lex_state = 0, .external_lex_state = 8},
  [161] = {.lex_state = 2},
  [162] = {.lex_state = 0, .external_lex_state = 7},
  [163] = {.lex_state = 0, .external_lex_state = 7},
  [164] = {.lex_state = 0, .external_lex_state = 7},
  [165] = {.lex_state = 0},
  [166] = {.lex_state = 0, .external_lex_state = 6},
  [167] = {.lex_state = 0, .external_lex_state = 6},
  [168] = {.lex_state = 2},
  [169] = {.lex_state = 0},
  [170] = {.lex_state = 2},
  [171] = {.lex_state = 2},
  [172] = {.lex_state = 0, .external_lex_state = 7},
  [173] = {.lex_state = 0, .external_lex_state = 7},
  [174] = {.lex_state = 2},
  [175] = {.lex_state = 2},
  [176] = {.lex_state = 2},
  [177] = {.lex_state = 0},
  [178] = {.lex_state = 0, .external_lex_state = 7},
  [179] = {.lex_state = 2},
  [180] = {.lex_state = 2},
  [181] = {.lex_state = 0, .external_lex_state = 7},
};

enum {
  ts_external_token__name_ = 0,
  ts_external_token__indent_ = 1,
  ts_external_token__dedent_ = 2,
  ts_external_token__samedent_ = 3,
  ts_external_token__newline_ = 4,
  ts_external_token__line_ending_ = 5,
  ts_external_token__end_of_file_ = 6,
  ts_external_token__multiline_spacing_ = 7,
  ts_external_token__inline_spacing_ = 8,
  ts_external_token__error_ = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__name_] = sym__name_,
  [ts_external_token__indent_] = sym__indent_,
  [ts_external_token__dedent_] = sym__dedent_,
  [ts_external_token__samedent_] = sym__samedent_,
  [ts_external_token__newline_] = sym__newline_,
  [ts_external_token__line_ending_] = sym__line_ending_,
  [ts_external_token__end_of_file_] = sym__end_of_file_,
  [ts_external_token__multiline_spacing_] = sym__multiline_spacing_,
  [ts_external_token__inline_spacing_] = sym__inline_spacing_,
  [ts_external_token__error_] = sym__error_,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__name_] = true,
    [ts_external_token__indent_] = true,
    [ts_external_token__dedent_] = true,
    [ts_external_token__samedent_] = true,
    [ts_external_token__newline_] = true,
    [ts_external_token__line_ending_] = true,
    [ts_external_token__end_of_file_] = true,
    [ts_external_token__multiline_spacing_] = true,
    [ts_external_token__inline_spacing_] = true,
    [ts_external_token__error_] = true,
  },
  [2] = {
    [ts_external_token__name_] = true,
    [ts_external_token__line_ending_] = true,
    [ts_external_token__end_of_file_] = true,
  },
  [3] = {
    [ts_external_token__name_] = true,
  },
  [4] = {
    [ts_external_token__name_] = true,
    [ts_external_token__samedent_] = true,
    [ts_external_token__line_ending_] = true,
  },
  [5] = {
    [ts_external_token__line_ending_] = true,
    [ts_external_token__end_of_file_] = true,
  },
  [6] = {
    [ts_external_token__line_ending_] = true,
  },
  [7] = {
    [ts_external_token__samedent_] = true,
  },
  [8] = {
    [ts_external_token__indent_] = true,
  },
  [9] = {
    [ts_external_token__end_of_file_] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_assignment_operator] = ACTIONS(1),
    [aux_sym__inline_value_token1] = ACTIONS(1),
    [aux_sym__multiline_empty_token1] = ACTIONS(1),
    [aux_sym__inline_empty_token1] = ACTIONS(1),
    [aux_sym__integer_token1] = ACTIONS(1),
    [aux_sym__signed_integer_token1] = ACTIONS(1),
    [aux_sym__signed_integer_token2] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__name_] = ACTIONS(1),
    [sym__indent_] = ACTIONS(1),
    [sym__dedent_] = ACTIONS(1),
    [sym__samedent_] = ACTIONS(1),
    [sym__newline_] = ACTIONS(1),
    [sym__line_ending_] = ACTIONS(1),
    [sym__end_of_file_] = ACTIONS(1),
    [sym__multiline_spacing_] = ACTIONS(1),
    [sym__inline_spacing_] = ACTIONS(1),
    [sym__error_] = ACTIONS(1),
  },
  [1] = {
    [sym_src] = STATE(177),
    [sym__line_ending] = STATE(2),
    [sym__end_of_file] = STATE(27),
    [sym__struct] = STATE(26),
    [sym_map] = STATE(26),
    [sym__multiline_map] = STATE(97),
    [sym__multiline_map_entry] = STATE(12),
    [sym__multiline_map_named_entry] = STATE(38),
    [sym_name] = STATE(171),
    [sym__multiline_literal] = STATE(26),
    [sym__inline_literal] = STATE(26),
    [sym__multiline_empty] = STATE(95),
    [sym__inline_empty] = STATE(94),
    [sym__inline_number] = STATE(94),
    [sym__signed_number] = STATE(93),
    [sym__unsigned_number] = STATE(93),
    [sym__integer] = STATE(54),
    [sym__signed_integer] = STATE(53),
    [sym__decimal] = STATE(92),
    [sym__signed_decimal] = STATE(91),
    [sym__inline_text] = STATE(94),
    [aux_sym_src_repeat1] = STATE(2),
    [aux_sym__multiline_empty_token1] = ACTIONS(3),
    [aux_sym__inline_empty_token1] = ACTIONS(5),
    [aux_sym__integer_token1] = ACTIONS(7),
    [aux_sym__signed_integer_token1] = ACTIONS(9),
    [aux_sym__inline_text_token1] = ACTIONS(11),
    [sym__name_] = ACTIONS(13),
    [sym__line_ending_] = ACTIONS(15),
    [sym__end_of_file_] = ACTIONS(17),
  },
  [2] = {
    [sym__line_ending] = STATE(9),
    [sym__end_of_file] = STATE(28),
    [sym__struct] = STATE(29),
    [sym_map] = STATE(29),
    [sym__multiline_map] = STATE(97),
    [sym__multiline_map_entry] = STATE(12),
    [sym__multiline_map_named_entry] = STATE(38),
    [sym_name] = STATE(171),
    [sym__multiline_literal] = STATE(29),
    [sym__inline_literal] = STATE(29),
    [sym__multiline_empty] = STATE(95),
    [sym__inline_empty] = STATE(94),
    [sym__inline_number] = STATE(94),
    [sym__signed_number] = STATE(93),
    [sym__unsigned_number] = STATE(93),
    [sym__integer] = STATE(54),
    [sym__signed_integer] = STATE(53),
    [sym__decimal] = STATE(92),
    [sym__signed_decimal] = STATE(91),
    [sym__inline_text] = STATE(94),
    [aux_sym_src_repeat1] = STATE(9),
    [aux_sym__multiline_empty_token1] = ACTIONS(3),
    [aux_sym__inline_empty_token1] = ACTIONS(5),
    [aux_sym__integer_token1] = ACTIONS(7),
    [aux_sym__signed_integer_token1] = ACTIONS(9),
    [aux_sym__inline_text_token1] = ACTIONS(11),
    [sym__name_] = ACTIONS(13),
    [sym__line_ending_] = ACTIONS(15),
    [sym__end_of_file_] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(19), 1,
      aux_sym__multiline_empty_token1,
    ACTIONS(21), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(23), 1,
      aux_sym__integer_token1,
    ACTIONS(25), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(27), 1,
      aux_sym__inline_text_token1,
    STATE(17), 1,
      sym__multiline_map_entry,
    STATE(43), 1,
      sym__signed_integer,
    STATE(46), 1,
      sym__integer,
    STATE(73), 1,
      sym__multiline_empty,
    STATE(75), 1,
      sym__multiline_map,
    STATE(86), 1,
      sym__decimal,
    STATE(87), 1,
      sym__signed_decimal,
    STATE(96), 1,
      sym__multiline_map_named_entry,
    STATE(179), 1,
      sym_name,
    STATE(81), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(74), 3,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
    STATE(77), 3,
      sym_map,
      sym__multiline_literal,
      sym__inline_literal,
  [60] = 18,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(29), 1,
      aux_sym__multiline_empty_token1,
    ACTIONS(31), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(33), 1,
      aux_sym__integer_token1,
    ACTIONS(35), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(37), 1,
      aux_sym__inline_text_token1,
    STATE(13), 1,
      sym__multiline_map_entry,
    STATE(30), 1,
      sym__signed_integer,
    STATE(37), 1,
      sym__integer,
    STATE(38), 1,
      sym__multiline_map_named_entry,
    STATE(44), 1,
      sym__signed_decimal,
    STATE(49), 1,
      sym__decimal,
    STATE(60), 1,
      sym__multiline_map,
    STATE(62), 1,
      sym__multiline_empty,
    STATE(171), 1,
      sym_name,
    STATE(39), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(57), 3,
      sym_map,
      sym__multiline_literal,
      sym__inline_literal,
    STATE(64), 3,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [120] = 18,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(39), 1,
      aux_sym__multiline_empty_token1,
    ACTIONS(41), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(43), 1,
      aux_sym__integer_token1,
    ACTIONS(45), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(47), 1,
      aux_sym__inline_text_token1,
    STATE(15), 1,
      sym__multiline_map_entry,
    STATE(96), 1,
      sym__multiline_map_named_entry,
    STATE(131), 1,
      sym__integer,
    STATE(132), 1,
      sym__signed_integer,
    STATE(136), 1,
      sym__multiline_empty,
    STATE(137), 1,
      sym__signed_decimal,
    STATE(158), 1,
      sym__decimal,
    STATE(178), 1,
      sym__multiline_map,
    STATE(179), 1,
      sym_name,
    STATE(149), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(151), 3,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
    STATE(172), 3,
      sym_map,
      sym__multiline_literal,
      sym__inline_literal,
  [180] = 11,
    ACTIONS(49), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(51), 1,
      aux_sym__integer_token1,
    ACTIONS(53), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(55), 1,
      aux_sym__inline_text_token1,
    STATE(102), 1,
      sym__integer,
    STATE(107), 1,
      sym__inline_literal,
    STATE(128), 1,
      sym__signed_integer,
    STATE(152), 1,
      sym__decimal,
    STATE(155), 1,
      sym__signed_decimal,
    STATE(138), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(139), 3,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [217] = 11,
    ACTIONS(49), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(51), 1,
      aux_sym__integer_token1,
    ACTIONS(53), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(55), 1,
      aux_sym__inline_text_token1,
    STATE(102), 1,
      sym__integer,
    STATE(128), 1,
      sym__signed_integer,
    STATE(129), 1,
      sym__inline_literal,
    STATE(152), 1,
      sym__decimal,
    STATE(155), 1,
      sym__signed_decimal,
    STATE(138), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(139), 3,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [254] = 11,
    ACTIONS(49), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(51), 1,
      aux_sym__integer_token1,
    ACTIONS(53), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(55), 1,
      aux_sym__inline_text_token1,
    STATE(102), 1,
      sym__integer,
    STATE(110), 1,
      sym__inline_literal,
    STATE(128), 1,
      sym__signed_integer,
    STATE(152), 1,
      sym__decimal,
    STATE(155), 1,
      sym__signed_decimal,
    STATE(138), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(139), 3,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [291] = 4,
    ACTIONS(61), 1,
      sym__line_ending_,
    ACTIONS(59), 2,
      sym__name_,
      sym__end_of_file_,
    STATE(9), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
    ACTIONS(57), 5,
      aux_sym__multiline_empty_token1,
      aux_sym__inline_empty_token1,
      aux_sym__integer_token1,
      aux_sym__signed_integer_token1,
      aux_sym__inline_text_token1,
  [310] = 6,
    STATE(18), 1,
      aux_sym__multiline_map_repeat1,
    STATE(115), 1,
      sym__line_ending,
    STATE(117), 1,
      sym__multiline_map_entry,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
    ACTIONS(64), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [332] = 7,
    ACTIONS(13), 1,
      sym__name_,
    STATE(18), 1,
      aux_sym__multiline_map_repeat1,
    STATE(117), 1,
      sym__multiline_map_entry,
    STATE(126), 1,
      sym__line_ending,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
    ACTIONS(64), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [356] = 7,
    ACTIONS(13), 1,
      sym__name_,
    STATE(11), 1,
      aux_sym__multiline_map_repeat1,
    STATE(113), 1,
      sym__line_ending,
    STATE(117), 1,
      sym__multiline_map_entry,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
    ACTIONS(66), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [380] = 6,
    STATE(10), 1,
      aux_sym__multiline_map_repeat1,
    STATE(117), 1,
      sym__multiline_map_entry,
    STATE(119), 1,
      sym__line_ending,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
    ACTIONS(66), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [402] = 2,
    ACTIONS(70), 3,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
    ACTIONS(68), 5,
      aux_sym__multiline_empty_token1,
      aux_sym__inline_empty_token1,
      aux_sym__integer_token1,
      aux_sym__signed_integer_token1,
      aux_sym__inline_text_token1,
  [415] = 8,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(66), 1,
      sym__samedent_,
    ACTIONS(72), 1,
      sym__line_ending_,
    STATE(19), 1,
      aux_sym__multiline_map_repeat1,
    STATE(109), 1,
      sym__line_ending,
    STATE(114), 1,
      sym__multiline_map_entry,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
  [440] = 6,
    STATE(20), 1,
      aux_sym__multiline_map_repeat1,
    STATE(105), 1,
      sym__line_ending,
    STATE(114), 1,
      sym__multiline_map_entry,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
    ACTIONS(64), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [461] = 6,
    STATE(16), 1,
      aux_sym__multiline_map_repeat1,
    STATE(106), 1,
      sym__line_ending,
    STATE(114), 1,
      sym__multiline_map_entry,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
    ACTIONS(66), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [482] = 6,
    ACTIONS(76), 1,
      sym__name_,
    STATE(18), 1,
      aux_sym__multiline_map_repeat1,
    STATE(117), 1,
      sym__multiline_map_entry,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
    ACTIONS(74), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [503] = 8,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(64), 1,
      sym__samedent_,
    ACTIONS(72), 1,
      sym__line_ending_,
    STATE(20), 1,
      aux_sym__multiline_map_repeat1,
    STATE(108), 1,
      sym__line_ending,
    STATE(114), 1,
      sym__multiline_map_entry,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
  [528] = 6,
    ACTIONS(76), 1,
      sym__name_,
    STATE(20), 1,
      aux_sym__multiline_map_repeat1,
    STATE(114), 1,
      sym__multiline_map_entry,
    STATE(142), 1,
      sym__multiline_map_named_entry,
    STATE(176), 1,
      sym_name,
    ACTIONS(74), 2,
      sym__samedent_,
      sym__line_ending_,
  [548] = 5,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    STATE(154), 1,
      sym__end_of_file,
    STATE(34), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [565] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(148), 1,
      sym__end_of_file,
    STATE(34), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [582] = 2,
    ACTIONS(89), 1,
      sym__name_,
    ACTIONS(87), 5,
      aux_sym__multiline_empty_token1,
      aux_sym__inline_empty_token1,
      aux_sym__integer_token1,
      aux_sym__signed_integer_token1,
      aux_sym__inline_text_token1,
  [593] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    STATE(147), 1,
      sym__end_of_file,
    STATE(34), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [610] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    STATE(153), 1,
      sym__end_of_file,
    STATE(34), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [627] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    STATE(165), 1,
      sym__end_of_file,
    STATE(25), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [644] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    STATE(169), 1,
      sym__end_of_file,
    STATE(21), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [661] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    STATE(150), 1,
      sym__end_of_file,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [678] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    STATE(153), 1,
      sym__end_of_file,
    STATE(24), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [695] = 2,
    ACTIONS(103), 1,
      anon_sym_DOT,
    ACTIONS(101), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [705] = 1,
    ACTIONS(105), 5,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [713] = 4,
    ACTIONS(107), 1,
      aux_sym__inline_value_token1,
    ACTIONS(109), 1,
      sym__line_ending_,
    STATE(103), 1,
      sym__line_ending,
    STATE(85), 2,
      sym__inline_value,
      sym__child_value,
  [727] = 4,
    ACTIONS(109), 1,
      sym__line_ending_,
    ACTIONS(111), 1,
      aux_sym__inline_value_token1,
    STATE(104), 1,
      sym__line_ending,
    STATE(163), 2,
      sym__inline_value,
      sym__child_value,
  [741] = 3,
    ACTIONS(113), 1,
      sym__line_ending_,
    ACTIONS(59), 2,
      sym__end_of_file_,
      ts_builtin_sym_end,
    STATE(34), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [753] = 1,
    ACTIONS(116), 5,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [761] = 4,
    ACTIONS(109), 1,
      sym__line_ending_,
    ACTIONS(118), 1,
      aux_sym__inline_value_token1,
    STATE(127), 1,
      sym__line_ending,
    STATE(47), 2,
      sym__inline_value,
      sym__child_value,
  [775] = 2,
    ACTIONS(122), 1,
      anon_sym_DOT,
    ACTIONS(120), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [785] = 1,
    ACTIONS(124), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [792] = 1,
    ACTIONS(126), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [799] = 1,
    ACTIONS(128), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [806] = 1,
    ACTIONS(116), 4,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
      anon_sym_DOT,
  [813] = 1,
    ACTIONS(74), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [820] = 2,
    ACTIONS(130), 1,
      anon_sym_DOT,
    ACTIONS(101), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [829] = 1,
    ACTIONS(101), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [836] = 1,
    ACTIONS(116), 4,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [843] = 2,
    ACTIONS(132), 1,
      anon_sym_DOT,
    ACTIONS(120), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [852] = 1,
    ACTIONS(134), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [859] = 1,
    ACTIONS(136), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [866] = 1,
    ACTIONS(120), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [873] = 1,
    ACTIONS(138), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [880] = 1,
    ACTIONS(140), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [887] = 1,
    ACTIONS(142), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [894] = 2,
    ACTIONS(144), 1,
      anon_sym_DOT,
    ACTIONS(101), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [903] = 2,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(120), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [912] = 1,
    ACTIONS(105), 4,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
      anon_sym_DOT,
  [919] = 1,
    ACTIONS(148), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [926] = 1,
    ACTIONS(150), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [933] = 1,
    ACTIONS(152), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [940] = 1,
    ACTIONS(70), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [947] = 1,
    ACTIONS(154), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [954] = 1,
    ACTIONS(156), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [961] = 1,
    ACTIONS(158), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [968] = 1,
    ACTIONS(160), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [975] = 1,
    ACTIONS(162), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [982] = 1,
    ACTIONS(105), 4,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [989] = 1,
    ACTIONS(138), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [995] = 1,
    ACTIONS(160), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1001] = 1,
    ACTIONS(70), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1007] = 1,
    ACTIONS(128), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1013] = 1,
    ACTIONS(156), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1019] = 1,
    ACTIONS(140), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1025] = 1,
    ACTIONS(142), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1031] = 1,
    ACTIONS(158), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1037] = 1,
    ACTIONS(162), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1043] = 1,
    ACTIONS(154), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1049] = 1,
    ACTIONS(152), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1055] = 1,
    ACTIONS(150), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1061] = 1,
    ACTIONS(148), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1067] = 1,
    ACTIONS(140), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1073] = 1,
    ACTIONS(142), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1079] = 1,
    ACTIONS(126), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1085] = 1,
    ACTIONS(136), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1091] = 1,
    ACTIONS(128), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1097] = 1,
    ACTIONS(74), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1103] = 1,
    ACTIONS(134), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1109] = 1,
    ACTIONS(120), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1115] = 1,
    ACTIONS(101), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1121] = 1,
    ACTIONS(136), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1127] = 1,
    ACTIONS(138), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1133] = 1,
    ACTIONS(70), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1139] = 1,
    ACTIONS(101), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1145] = 1,
    ACTIONS(120), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1151] = 1,
    ACTIONS(126), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1157] = 1,
    ACTIONS(162), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1163] = 1,
    ACTIONS(158), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1169] = 1,
    ACTIONS(124), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1175] = 1,
    ACTIONS(154), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1181] = 1,
    ACTIONS(160), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1187] = 1,
    ACTIONS(156), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1193] = 1,
    ACTIONS(152), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1199] = 1,
    ACTIONS(116), 2,
      sym__samedent_,
      anon_sym_DOT,
  [1204] = 2,
    ACTIONS(120), 1,
      sym__line_ending_,
    ACTIONS(164), 1,
      anon_sym_DOT,
  [1211] = 2,
    ACTIONS(166), 1,
      sym__indent_,
    STATE(3), 1,
      sym__increase_indent,
  [1218] = 2,
    ACTIONS(166), 1,
      sym__indent_,
    STATE(5), 1,
      sym__increase_indent,
  [1225] = 2,
    ACTIONS(168), 1,
      sym__end_of_file_,
    STATE(79), 1,
      sym__end_of_file,
  [1232] = 2,
    ACTIONS(168), 1,
      sym__end_of_file_,
    STATE(69), 1,
      sym__end_of_file,
  [1239] = 2,
    ACTIONS(170), 1,
      sym__line_ending_,
    STATE(78), 1,
      sym__line_ending,
  [1246] = 2,
    ACTIONS(172), 1,
      sym__end_of_file_,
    STATE(162), 1,
      sym__end_of_file,
  [1253] = 2,
    ACTIONS(172), 1,
      sym__end_of_file_,
    STATE(164), 1,
      sym__end_of_file,
  [1260] = 2,
    ACTIONS(174), 1,
      sym__line_ending_,
    STATE(181), 1,
      sym__line_ending,
  [1267] = 2,
    ACTIONS(176), 1,
      aux_sym__integer_token1,
    STATE(48), 1,
      sym__integer,
  [1274] = 2,
    ACTIONS(176), 1,
      aux_sym__integer_token1,
    STATE(50), 1,
      sym__integer,
  [1281] = 2,
    ACTIONS(17), 1,
      sym__end_of_file_,
    STATE(83), 1,
      sym__end_of_file,
  [1288] = 2,
    ACTIONS(178), 1,
      sym__samedent_,
    STATE(84), 1,
      sym__current_indent,
  [1295] = 2,
    ACTIONS(180), 1,
      sym__end_of_file_,
    STATE(51), 1,
      sym__end_of_file,
  [1302] = 2,
    ACTIONS(182), 1,
      aux_sym__integer_token1,
    STATE(167), 1,
      sym__integer,
  [1309] = 2,
    ACTIONS(184), 1,
      sym__samedent_,
    STATE(42), 1,
      sym__current_indent,
  [1316] = 2,
    ACTIONS(182), 1,
      aux_sym__integer_token1,
    STATE(166), 1,
      sym__integer,
  [1323] = 2,
    ACTIONS(180), 1,
      sym__end_of_file_,
    STATE(40), 1,
      sym__end_of_file,
  [1330] = 2,
    ACTIONS(186), 1,
      aux_sym__integer_token1,
    STATE(82), 1,
      sym__integer,
  [1337] = 2,
    ACTIONS(186), 1,
      aux_sym__integer_token1,
    STATE(66), 1,
      sym__integer,
  [1344] = 1,
    ACTIONS(116), 2,
      sym__line_ending_,
      anon_sym_DOT,
  [1349] = 2,
    ACTIONS(188), 1,
      aux_sym__integer_token1,
    STATE(89), 1,
      sym__integer,
  [1356] = 1,
    ACTIONS(105), 2,
      sym__samedent_,
      anon_sym_DOT,
  [1361] = 2,
    ACTIONS(188), 1,
      aux_sym__integer_token1,
    STATE(88), 1,
      sym__integer,
  [1368] = 2,
    ACTIONS(17), 1,
      sym__end_of_file_,
    STATE(71), 1,
      sym__end_of_file,
  [1375] = 2,
    ACTIONS(166), 1,
      sym__indent_,
    STATE(4), 1,
      sym__increase_indent,
  [1382] = 2,
    ACTIONS(101), 1,
      sym__line_ending_,
    ACTIONS(190), 1,
      anon_sym_DOT,
  [1389] = 2,
    ACTIONS(192), 1,
      sym__line_ending_,
    STATE(56), 1,
      sym__line_ending,
  [1396] = 1,
    ACTIONS(105), 2,
      sym__line_ending_,
      anon_sym_DOT,
  [1401] = 2,
    ACTIONS(120), 1,
      sym__samedent_,
    ACTIONS(194), 1,
      anon_sym_DOT,
  [1408] = 2,
    ACTIONS(101), 1,
      sym__samedent_,
    ACTIONS(196), 1,
      anon_sym_DOT,
  [1415] = 2,
    ACTIONS(198), 1,
      aux_sym__integer_token1,
    STATE(141), 1,
      sym__integer,
  [1422] = 2,
    ACTIONS(198), 1,
      aux_sym__integer_token1,
    STATE(140), 1,
      sym__integer,
  [1429] = 1,
    ACTIONS(142), 1,
      sym__samedent_,
  [1433] = 1,
    ACTIONS(158), 1,
      sym__samedent_,
  [1437] = 1,
    ACTIONS(101), 1,
      sym__samedent_,
  [1441] = 1,
    ACTIONS(126), 1,
      sym__line_ending_,
  [1445] = 1,
    ACTIONS(162), 1,
      sym__line_ending_,
  [1449] = 1,
    ACTIONS(136), 1,
      sym__samedent_,
  [1453] = 1,
    ACTIONS(138), 1,
      sym__samedent_,
  [1457] = 1,
    ACTIONS(124), 1,
      sym__samedent_,
  [1461] = 1,
    ACTIONS(160), 1,
      sym__line_ending_,
  [1465] = 1,
    ACTIONS(70), 1,
      sym__end_of_file_,
  [1469] = 1,
    ACTIONS(156), 1,
      sym__line_ending_,
  [1473] = 1,
    ACTIONS(142), 1,
      ts_builtin_sym_end,
  [1477] = 1,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
  [1481] = 1,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
  [1485] = 1,
    ACTIONS(126), 1,
      sym__samedent_,
  [1489] = 1,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [1493] = 1,
    ACTIONS(162), 1,
      sym__samedent_,
  [1497] = 1,
    ACTIONS(120), 1,
      sym__line_ending_,
  [1501] = 1,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
  [1505] = 1,
    ACTIONS(204), 1,
      ts_builtin_sym_end,
  [1509] = 1,
    ACTIONS(101), 1,
      sym__line_ending_,
  [1513] = 1,
    ACTIONS(160), 1,
      sym__samedent_,
  [1517] = 1,
    ACTIONS(156), 1,
      sym__samedent_,
  [1521] = 1,
    ACTIONS(120), 1,
      sym__samedent_,
  [1525] = 1,
    ACTIONS(70), 1,
      sym__samedent_,
  [1529] = 1,
    ACTIONS(70), 1,
      sym__indent_,
  [1533] = 1,
    ACTIONS(206), 1,
      aux_sym__signed_integer_token2,
  [1537] = 1,
    ACTIONS(140), 1,
      sym__samedent_,
  [1541] = 1,
    ACTIONS(134), 1,
      sym__samedent_,
  [1545] = 1,
    ACTIONS(128), 1,
      sym__samedent_,
  [1549] = 1,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
  [1553] = 1,
    ACTIONS(136), 1,
      sym__line_ending_,
  [1557] = 1,
    ACTIONS(138), 1,
      sym__line_ending_,
  [1561] = 1,
    ACTIONS(208), 1,
      aux_sym__signed_integer_token2,
  [1565] = 1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
  [1569] = 1,
    ACTIONS(210), 1,
      sym_assignment_operator,
  [1573] = 1,
    ACTIONS(212), 1,
      sym_assignment_operator,
  [1577] = 1,
    ACTIONS(150), 1,
      sym__samedent_,
  [1581] = 1,
    ACTIONS(152), 1,
      sym__samedent_,
  [1585] = 1,
    ACTIONS(214), 1,
      aux_sym__signed_integer_token2,
  [1589] = 1,
    ACTIONS(216), 1,
      aux_sym__signed_integer_token2,
  [1593] = 1,
    ACTIONS(218), 1,
      sym_assignment_operator,
  [1597] = 1,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
  [1601] = 1,
    ACTIONS(154), 1,
      sym__samedent_,
  [1605] = 1,
    ACTIONS(222), 1,
      sym_assignment_operator,
  [1609] = 1,
    ACTIONS(224), 1,
      aux_sym__signed_integer_token2,
  [1613] = 1,
    ACTIONS(148), 1,
      sym__samedent_,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 60,
  [SMALL_STATE(5)] = 120,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 217,
  [SMALL_STATE(8)] = 254,
  [SMALL_STATE(9)] = 291,
  [SMALL_STATE(10)] = 310,
  [SMALL_STATE(11)] = 332,
  [SMALL_STATE(12)] = 356,
  [SMALL_STATE(13)] = 380,
  [SMALL_STATE(14)] = 402,
  [SMALL_STATE(15)] = 415,
  [SMALL_STATE(16)] = 440,
  [SMALL_STATE(17)] = 461,
  [SMALL_STATE(18)] = 482,
  [SMALL_STATE(19)] = 503,
  [SMALL_STATE(20)] = 528,
  [SMALL_STATE(21)] = 548,
  [SMALL_STATE(22)] = 565,
  [SMALL_STATE(23)] = 582,
  [SMALL_STATE(24)] = 593,
  [SMALL_STATE(25)] = 610,
  [SMALL_STATE(26)] = 627,
  [SMALL_STATE(27)] = 644,
  [SMALL_STATE(28)] = 661,
  [SMALL_STATE(29)] = 678,
  [SMALL_STATE(30)] = 695,
  [SMALL_STATE(31)] = 705,
  [SMALL_STATE(32)] = 713,
  [SMALL_STATE(33)] = 727,
  [SMALL_STATE(34)] = 741,
  [SMALL_STATE(35)] = 753,
  [SMALL_STATE(36)] = 761,
  [SMALL_STATE(37)] = 775,
  [SMALL_STATE(38)] = 785,
  [SMALL_STATE(39)] = 792,
  [SMALL_STATE(40)] = 799,
  [SMALL_STATE(41)] = 806,
  [SMALL_STATE(42)] = 813,
  [SMALL_STATE(43)] = 820,
  [SMALL_STATE(44)] = 829,
  [SMALL_STATE(45)] = 836,
  [SMALL_STATE(46)] = 843,
  [SMALL_STATE(47)] = 852,
  [SMALL_STATE(48)] = 859,
  [SMALL_STATE(49)] = 866,
  [SMALL_STATE(50)] = 873,
  [SMALL_STATE(51)] = 880,
  [SMALL_STATE(52)] = 887,
  [SMALL_STATE(53)] = 894,
  [SMALL_STATE(54)] = 903,
  [SMALL_STATE(55)] = 912,
  [SMALL_STATE(56)] = 919,
  [SMALL_STATE(57)] = 926,
  [SMALL_STATE(58)] = 933,
  [SMALL_STATE(59)] = 940,
  [SMALL_STATE(60)] = 947,
  [SMALL_STATE(61)] = 954,
  [SMALL_STATE(62)] = 961,
  [SMALL_STATE(63)] = 968,
  [SMALL_STATE(64)] = 975,
  [SMALL_STATE(65)] = 982,
  [SMALL_STATE(66)] = 989,
  [SMALL_STATE(67)] = 995,
  [SMALL_STATE(68)] = 1001,
  [SMALL_STATE(69)] = 1007,
  [SMALL_STATE(70)] = 1013,
  [SMALL_STATE(71)] = 1019,
  [SMALL_STATE(72)] = 1025,
  [SMALL_STATE(73)] = 1031,
  [SMALL_STATE(74)] = 1037,
  [SMALL_STATE(75)] = 1043,
  [SMALL_STATE(76)] = 1049,
  [SMALL_STATE(77)] = 1055,
  [SMALL_STATE(78)] = 1061,
  [SMALL_STATE(79)] = 1067,
  [SMALL_STATE(80)] = 1073,
  [SMALL_STATE(81)] = 1079,
  [SMALL_STATE(82)] = 1085,
  [SMALL_STATE(83)] = 1091,
  [SMALL_STATE(84)] = 1097,
  [SMALL_STATE(85)] = 1103,
  [SMALL_STATE(86)] = 1109,
  [SMALL_STATE(87)] = 1115,
  [SMALL_STATE(88)] = 1121,
  [SMALL_STATE(89)] = 1127,
  [SMALL_STATE(90)] = 1133,
  [SMALL_STATE(91)] = 1139,
  [SMALL_STATE(92)] = 1145,
  [SMALL_STATE(93)] = 1151,
  [SMALL_STATE(94)] = 1157,
  [SMALL_STATE(95)] = 1163,
  [SMALL_STATE(96)] = 1169,
  [SMALL_STATE(97)] = 1175,
  [SMALL_STATE(98)] = 1181,
  [SMALL_STATE(99)] = 1187,
  [SMALL_STATE(100)] = 1193,
  [SMALL_STATE(101)] = 1199,
  [SMALL_STATE(102)] = 1204,
  [SMALL_STATE(103)] = 1211,
  [SMALL_STATE(104)] = 1218,
  [SMALL_STATE(105)] = 1225,
  [SMALL_STATE(106)] = 1232,
  [SMALL_STATE(107)] = 1239,
  [SMALL_STATE(108)] = 1246,
  [SMALL_STATE(109)] = 1253,
  [SMALL_STATE(110)] = 1260,
  [SMALL_STATE(111)] = 1267,
  [SMALL_STATE(112)] = 1274,
  [SMALL_STATE(113)] = 1281,
  [SMALL_STATE(114)] = 1288,
  [SMALL_STATE(115)] = 1295,
  [SMALL_STATE(116)] = 1302,
  [SMALL_STATE(117)] = 1309,
  [SMALL_STATE(118)] = 1316,
  [SMALL_STATE(119)] = 1323,
  [SMALL_STATE(120)] = 1330,
  [SMALL_STATE(121)] = 1337,
  [SMALL_STATE(122)] = 1344,
  [SMALL_STATE(123)] = 1349,
  [SMALL_STATE(124)] = 1356,
  [SMALL_STATE(125)] = 1361,
  [SMALL_STATE(126)] = 1368,
  [SMALL_STATE(127)] = 1375,
  [SMALL_STATE(128)] = 1382,
  [SMALL_STATE(129)] = 1389,
  [SMALL_STATE(130)] = 1396,
  [SMALL_STATE(131)] = 1401,
  [SMALL_STATE(132)] = 1408,
  [SMALL_STATE(133)] = 1415,
  [SMALL_STATE(134)] = 1422,
  [SMALL_STATE(135)] = 1429,
  [SMALL_STATE(136)] = 1433,
  [SMALL_STATE(137)] = 1437,
  [SMALL_STATE(138)] = 1441,
  [SMALL_STATE(139)] = 1445,
  [SMALL_STATE(140)] = 1449,
  [SMALL_STATE(141)] = 1453,
  [SMALL_STATE(142)] = 1457,
  [SMALL_STATE(143)] = 1461,
  [SMALL_STATE(144)] = 1465,
  [SMALL_STATE(145)] = 1469,
  [SMALL_STATE(146)] = 1473,
  [SMALL_STATE(147)] = 1477,
  [SMALL_STATE(148)] = 1481,
  [SMALL_STATE(149)] = 1485,
  [SMALL_STATE(150)] = 1489,
  [SMALL_STATE(151)] = 1493,
  [SMALL_STATE(152)] = 1497,
  [SMALL_STATE(153)] = 1501,
  [SMALL_STATE(154)] = 1505,
  [SMALL_STATE(155)] = 1509,
  [SMALL_STATE(156)] = 1513,
  [SMALL_STATE(157)] = 1517,
  [SMALL_STATE(158)] = 1521,
  [SMALL_STATE(159)] = 1525,
  [SMALL_STATE(160)] = 1529,
  [SMALL_STATE(161)] = 1533,
  [SMALL_STATE(162)] = 1537,
  [SMALL_STATE(163)] = 1541,
  [SMALL_STATE(164)] = 1545,
  [SMALL_STATE(165)] = 1549,
  [SMALL_STATE(166)] = 1553,
  [SMALL_STATE(167)] = 1557,
  [SMALL_STATE(168)] = 1561,
  [SMALL_STATE(169)] = 1565,
  [SMALL_STATE(170)] = 1569,
  [SMALL_STATE(171)] = 1573,
  [SMALL_STATE(172)] = 1577,
  [SMALL_STATE(173)] = 1581,
  [SMALL_STATE(174)] = 1585,
  [SMALL_STATE(175)] = 1589,
  [SMALL_STATE(176)] = 1593,
  [SMALL_STATE(177)] = 1597,
  [SMALL_STATE(178)] = 1601,
  [SMALL_STATE(179)] = 1605,
  [SMALL_STATE(180)] = 1609,
  [SMALL_STATE(181)] = 1613,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(100),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(180),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(170),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(175),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(168),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(173),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(157),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(174),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(156),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(145),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(161),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(143),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_src_repeat1, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_src_repeat1, 2),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_src_repeat1, 2), SHIFT_REPEAT(14),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 2, .production_id = 5),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 1, .production_id = 2),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line_ending, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line_ending, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_map_repeat1, 2),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiline_map_repeat1, 2), SHIFT_REPEAT(170),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 2, .production_id = 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 3, .production_id = 6),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__increase_indent, 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__increase_indent, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 1, .production_id = 1),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 2, .production_id = 6),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__signed_number, 1),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__integer, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(160),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_src_repeat1, 2), SHIFT_REPEAT(68),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__signed_integer, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unsigned_number, 1, .production_id = 4),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map_entry, 1, .production_id = 3),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_number, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 3, .production_id = 7),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map_named_entry, 3, .production_id = 8),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 3),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__signed_decimal, 3, .production_id = 9),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 4, .production_id = 10),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_of_file, 1),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_value, 3, .production_id = 11),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__child_value, 3, .production_id = 12),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_empty, 1),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 1),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_empty, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_literal, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_text, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_literal, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(159),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 4),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 4, .production_id = 6),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 3, .production_id = 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [220] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_strux_external_scanner_create(void);
void tree_sitter_strux_external_scanner_destroy(void *);
bool tree_sitter_strux_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_strux_external_scanner_serialize(void *, char *);
void tree_sitter_strux_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_strux(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_strux_external_scanner_create,
      tree_sitter_strux_external_scanner_destroy,
      tree_sitter_strux_external_scanner_scan,
      tree_sitter_strux_external_scanner_serialize,
      tree_sitter_strux_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
