#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 151
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 6

enum {
  sym_assignment_operator = 1,
  aux_sym__inline_value_token1 = 2,
  aux_sym__multiline_empty_token1 = 3,
  aux_sym__inline_empty_token1 = 4,
  aux_sym__integer_token1 = 5,
  aux_sym__signed_integer_token1 = 6,
  anon_sym_DOT = 7,
  aux_sym__inline_text_token1 = 8,
  sym__name_ = 9,
  sym__indent_ = 10,
  sym__dedent_ = 11,
  sym__samedent_ = 12,
  sym__newline_ = 13,
  sym__line_ending_ = 14,
  sym__end_of_file_ = 15,
  sym__multiline_spacing_ = 16,
  sym__inline_spacing_ = 17,
  sym__error_ = 18,
  sym_src = 19,
  sym__current_indent = 20,
  sym__increase_indent = 21,
  sym__line_ending = 22,
  sym__end_of_file = 23,
  sym__struct = 24,
  sym_map = 25,
  sym__multiline_map = 26,
  sym__multiline_map_entry = 27,
  sym__multiline_map_named_entry = 28,
  sym_name = 29,
  sym__inline_value = 30,
  sym__child_value = 31,
  sym__multiline_literal = 32,
  sym__inline_literal = 33,
  sym__multiline_empty = 34,
  sym__inline_empty = 35,
  sym__inline_number = 36,
  sym__signed_number = 37,
  sym__unsigned_number = 38,
  sym__integer = 39,
  sym__signed_integer = 40,
  sym__decimal = 41,
  sym__signed_decimal = 42,
  sym__inline_text = 43,
  aux_sym_src_repeat1 = 44,
  aux_sym__multiline_map_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_assignment_operator] = "assignment_operator",
  [aux_sym__inline_value_token1] = "_inline_value_token1",
  [aux_sym__multiline_empty_token1] = "empty",
  [aux_sym__inline_empty_token1] = "empty",
  [aux_sym__integer_token1] = "integer",
  [aux_sym__signed_integer_token1] = "integer",
  [anon_sym_DOT] = ".",
  [aux_sym__inline_text_token1] = "text",
  [sym__name_] = "_name_",
  [sym__indent_] = "_indent_",
  [sym__dedent_] = "_dedent_",
  [sym__samedent_] = "_samedent_",
  [sym__newline_] = "_newline_",
  [sym__line_ending_] = "_line_ending_",
  [sym__end_of_file_] = "_end_of_file_",
  [sym__multiline_spacing_] = "_multiline_spacing_",
  [sym__inline_spacing_] = "_inline_spacing_",
  [sym__error_] = "_error_",
  [sym_src] = "src",
  [sym__current_indent] = "_current_indent",
  [sym__increase_indent] = "_increase_indent",
  [sym__line_ending] = "_line_ending",
  [sym__end_of_file] = "_end_of_file",
  [sym__struct] = "_struct",
  [sym_map] = "map",
  [sym__multiline_map] = "_multiline_map",
  [sym__multiline_map_entry] = "_multiline_map_entry",
  [sym__multiline_map_named_entry] = "named_entry",
  [sym_name] = "name",
  [sym__inline_value] = "_inline_value",
  [sym__child_value] = "_child_value",
  [sym__multiline_literal] = "_multiline_literal",
  [sym__inline_literal] = "_inline_literal",
  [sym__multiline_empty] = "_multiline_empty",
  [sym__inline_empty] = "literal",
  [sym__inline_number] = "literal",
  [sym__signed_number] = "number",
  [sym__unsigned_number] = "number",
  [sym__integer] = "_integer",
  [sym__signed_integer] = "_signed_integer",
  [sym__decimal] = "_decimal",
  [sym__signed_decimal] = "_signed_decimal",
  [sym__inline_text] = "literal",
  [aux_sym_src_repeat1] = "src_repeat1",
  [aux_sym__multiline_map_repeat1] = "_multiline_map_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_assignment_operator] = sym_assignment_operator,
  [aux_sym__inline_value_token1] = aux_sym__inline_value_token1,
  [aux_sym__multiline_empty_token1] = aux_sym__multiline_empty_token1,
  [aux_sym__inline_empty_token1] = aux_sym__multiline_empty_token1,
  [aux_sym__integer_token1] = aux_sym__integer_token1,
  [aux_sym__signed_integer_token1] = aux_sym__integer_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym__inline_text_token1] = aux_sym__inline_text_token1,
  [sym__name_] = sym__name_,
  [sym__indent_] = sym__indent_,
  [sym__dedent_] = sym__dedent_,
  [sym__samedent_] = sym__samedent_,
  [sym__newline_] = sym__newline_,
  [sym__line_ending_] = sym__line_ending_,
  [sym__end_of_file_] = sym__end_of_file_,
  [sym__multiline_spacing_] = sym__multiline_spacing_,
  [sym__inline_spacing_] = sym__inline_spacing_,
  [sym__error_] = sym__error_,
  [sym_src] = sym_src,
  [sym__current_indent] = sym__current_indent,
  [sym__increase_indent] = sym__increase_indent,
  [sym__line_ending] = sym__line_ending,
  [sym__end_of_file] = sym__end_of_file,
  [sym__struct] = sym__struct,
  [sym_map] = sym_map,
  [sym__multiline_map] = sym__multiline_map,
  [sym__multiline_map_entry] = sym__multiline_map_entry,
  [sym__multiline_map_named_entry] = sym__multiline_map_named_entry,
  [sym_name] = sym_name,
  [sym__inline_value] = sym__inline_value,
  [sym__child_value] = sym__child_value,
  [sym__multiline_literal] = sym__multiline_literal,
  [sym__inline_literal] = sym__inline_literal,
  [sym__multiline_empty] = sym__multiline_empty,
  [sym__inline_empty] = sym__inline_empty,
  [sym__inline_number] = sym__inline_empty,
  [sym__signed_number] = sym__signed_number,
  [sym__unsigned_number] = sym__signed_number,
  [sym__integer] = sym__integer,
  [sym__signed_integer] = sym__signed_integer,
  [sym__decimal] = sym__decimal,
  [sym__signed_decimal] = sym__signed_decimal,
  [sym__inline_text] = sym__inline_empty,
  [aux_sym_src_repeat1] = aux_sym_src_repeat1,
  [aux_sym__multiline_map_repeat1] = aux_sym__multiline_map_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__multiline_empty_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline_empty_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__integer_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__signed_integer_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__inline_text_token1] = {
    .visible = true,
    .named = true,
  },
  [sym__name_] = {
    .visible = false,
    .named = true,
  },
  [sym__indent_] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent_] = {
    .visible = false,
    .named = true,
  },
  [sym__samedent_] = {
    .visible = false,
    .named = true,
  },
  [sym__newline_] = {
    .visible = false,
    .named = true,
  },
  [sym__line_ending_] = {
    .visible = false,
    .named = true,
  },
  [sym__end_of_file_] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_spacing_] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_spacing_] = {
    .visible = false,
    .named = true,
  },
  [sym__error_] = {
    .visible = false,
    .named = true,
  },
  [sym_src] = {
    .visible = true,
    .named = true,
  },
  [sym__current_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__increase_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__line_ending] = {
    .visible = false,
    .named = true,
  },
  [sym__end_of_file] = {
    .visible = false,
    .named = true,
  },
  [sym__struct] = {
    .visible = false,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym__multiline_map] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_map_entry] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_map_named_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_value] = {
    .visible = false,
    .named = true,
  },
  [sym__child_value] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_empty] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_empty] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_number] = {
    .visible = true,
    .named = true,
  },
  [sym__signed_number] = {
    .visible = true,
    .named = true,
  },
  [sym__unsigned_number] = {
    .visible = true,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym__signed_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__decimal] = {
    .visible = false,
    .named = true,
  },
  [sym__signed_decimal] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_src_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__multiline_map_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_operator = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_operator] = "operator",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 3},
  [4] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0, .inherited = true},
    {field_operator, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [3] =
    {field_key, 0},
    {field_operator, 1},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = aux_sym__multiline_empty_token1,
  },
  [3] = {
    [1] = aux_sym__multiline_empty_token1,
  },
  [5] = {
    [0] = sym__inline_empty,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__end_of_file, 2,
    sym__end_of_file,
    aux_sym__multiline_empty_token1,
  sym__multiline_empty, 2,
    sym__multiline_empty,
    sym__inline_empty,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 3,
  [6] = 6,
  [7] = 6,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 10,
  [13] = 10,
  [14] = 11,
  [15] = 10,
  [16] = 16,
  [17] = 16,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 9,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 28,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 27,
  [35] = 35,
  [36] = 36,
  [37] = 31,
  [38] = 38,
  [39] = 31,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 27,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 53,
  [55] = 40,
  [56] = 52,
  [57] = 36,
  [58] = 51,
  [59] = 33,
  [60] = 49,
  [61] = 48,
  [62] = 47,
  [63] = 46,
  [64] = 45,
  [65] = 33,
  [66] = 41,
  [67] = 38,
  [68] = 36,
  [69] = 50,
  [70] = 40,
  [71] = 42,
  [72] = 32,
  [73] = 35,
  [74] = 53,
  [75] = 52,
  [76] = 35,
  [77] = 42,
  [78] = 50,
  [79] = 51,
  [80] = 45,
  [81] = 43,
  [82] = 38,
  [83] = 49,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 86,
  [88] = 84,
  [89] = 89,
  [90] = 90,
  [91] = 84,
  [92] = 89,
  [93] = 89,
  [94] = 94,
  [95] = 85,
  [96] = 94,
  [97] = 90,
  [98] = 85,
  [99] = 89,
  [100] = 100,
  [101] = 100,
  [102] = 94,
  [103] = 27,
  [104] = 31,
  [105] = 94,
  [106] = 85,
  [107] = 84,
  [108] = 86,
  [109] = 90,
  [110] = 94,
  [111] = 31,
  [112] = 27,
  [113] = 85,
  [114] = 35,
  [115] = 45,
  [116] = 42,
  [117] = 50,
  [118] = 38,
  [119] = 53,
  [120] = 52,
  [121] = 36,
  [122] = 122,
  [123] = 123,
  [124] = 43,
  [125] = 125,
  [126] = 45,
  [127] = 38,
  [128] = 128,
  [129] = 129,
  [130] = 50,
  [131] = 36,
  [132] = 42,
  [133] = 46,
  [134] = 33,
  [135] = 35,
  [136] = 40,
  [137] = 41,
  [138] = 138,
  [139] = 53,
  [140] = 140,
  [141] = 49,
  [142] = 142,
  [143] = 52,
  [144] = 48,
  [145] = 145,
  [146] = 145,
  [147] = 47,
  [148] = 145,
  [149] = 149,
  [150] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (eof) ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(7);
      END_STATE();
    case 1:
      if (eof) ADVANCE(3);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2)
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(2)
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_assignment_operator);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym__inline_value_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(9);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__inline_empty_token1);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__inline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym__signed_integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__inline_text_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym__inline_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 6, .external_lex_state = 2},
  [2] = {.lex_state = 6, .external_lex_state = 2},
  [3] = {.lex_state = 6, .external_lex_state = 3},
  [4] = {.lex_state = 6, .external_lex_state = 3},
  [5] = {.lex_state = 6, .external_lex_state = 3},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 6, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 4},
  [14] = {.lex_state = 0, .external_lex_state = 4},
  [15] = {.lex_state = 0, .external_lex_state = 4},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 4},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 5},
  [21] = {.lex_state = 0, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 5},
  [23] = {.lex_state = 0, .external_lex_state = 5},
  [24] = {.lex_state = 0, .external_lex_state = 5},
  [25] = {.lex_state = 0, .external_lex_state = 5},
  [26] = {.lex_state = 0, .external_lex_state = 5},
  [27] = {.lex_state = 1, .external_lex_state = 2},
  [28] = {.lex_state = 1, .external_lex_state = 6},
  [29] = {.lex_state = 1, .external_lex_state = 6},
  [30] = {.lex_state = 1, .external_lex_state = 6},
  [31] = {.lex_state = 1, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 1, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 1, .external_lex_state = 4},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 1, .external_lex_state = 5},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 1, .external_lex_state = 5},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 0, .external_lex_state = 2},
  [53] = {.lex_state = 0, .external_lex_state = 2},
  [54] = {.lex_state = 0, .external_lex_state = 5},
  [55] = {.lex_state = 0, .external_lex_state = 4},
  [56] = {.lex_state = 0, .external_lex_state = 5},
  [57] = {.lex_state = 0, .external_lex_state = 4},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 0, .external_lex_state = 4},
  [60] = {.lex_state = 0, .external_lex_state = 4},
  [61] = {.lex_state = 0, .external_lex_state = 4},
  [62] = {.lex_state = 0, .external_lex_state = 4},
  [63] = {.lex_state = 0, .external_lex_state = 4},
  [64] = {.lex_state = 0, .external_lex_state = 4},
  [65] = {.lex_state = 0, .external_lex_state = 5},
  [66] = {.lex_state = 0, .external_lex_state = 4},
  [67] = {.lex_state = 0, .external_lex_state = 4},
  [68] = {.lex_state = 0, .external_lex_state = 5},
  [69] = {.lex_state = 0, .external_lex_state = 4},
  [70] = {.lex_state = 0, .external_lex_state = 5},
  [71] = {.lex_state = 0, .external_lex_state = 4},
  [72] = {.lex_state = 0, .external_lex_state = 4},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 4},
  [75] = {.lex_state = 0, .external_lex_state = 4},
  [76] = {.lex_state = 0, .external_lex_state = 5},
  [77] = {.lex_state = 0, .external_lex_state = 5},
  [78] = {.lex_state = 0, .external_lex_state = 5},
  [79] = {.lex_state = 0, .external_lex_state = 5},
  [80] = {.lex_state = 0, .external_lex_state = 5},
  [81] = {.lex_state = 0, .external_lex_state = 4},
  [82] = {.lex_state = 0, .external_lex_state = 5},
  [83] = {.lex_state = 0, .external_lex_state = 5},
  [84] = {.lex_state = 0, .external_lex_state = 7},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0, .external_lex_state = 8},
  [87] = {.lex_state = 0, .external_lex_state = 8},
  [88] = {.lex_state = 0, .external_lex_state = 7},
  [89] = {.lex_state = 0, .external_lex_state = 7},
  [90] = {.lex_state = 0, .external_lex_state = 6},
  [91] = {.lex_state = 0, .external_lex_state = 7},
  [92] = {.lex_state = 0, .external_lex_state = 7},
  [93] = {.lex_state = 0, .external_lex_state = 7},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0, .external_lex_state = 6},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0, .external_lex_state = 7},
  [100] = {.lex_state = 0, .external_lex_state = 9},
  [101] = {.lex_state = 0, .external_lex_state = 9},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 1, .external_lex_state = 6},
  [104] = {.lex_state = 1, .external_lex_state = 6},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0, .external_lex_state = 7},
  [108] = {.lex_state = 0, .external_lex_state = 8},
  [109] = {.lex_state = 0, .external_lex_state = 6},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 1, .external_lex_state = 9},
  [112] = {.lex_state = 1, .external_lex_state = 9},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0, .external_lex_state = 9},
  [115] = {.lex_state = 0, .external_lex_state = 6},
  [116] = {.lex_state = 0, .external_lex_state = 9},
  [117] = {.lex_state = 0, .external_lex_state = 9},
  [118] = {.lex_state = 0, .external_lex_state = 6},
  [119] = {.lex_state = 0, .external_lex_state = 9},
  [120] = {.lex_state = 0, .external_lex_state = 9},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0, .external_lex_state = 9},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0, .external_lex_state = 9},
  [127] = {.lex_state = 0, .external_lex_state = 9},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0, .external_lex_state = 6},
  [131] = {.lex_state = 0, .external_lex_state = 9},
  [132] = {.lex_state = 0, .external_lex_state = 6},
  [133] = {.lex_state = 0, .external_lex_state = 9},
  [134] = {.lex_state = 0, .external_lex_state = 9},
  [135] = {.lex_state = 0, .external_lex_state = 6},
  [136] = {.lex_state = 0, .external_lex_state = 9},
  [137] = {.lex_state = 0, .external_lex_state = 9},
  [138] = {.lex_state = 1},
  [139] = {.lex_state = 0, .external_lex_state = 6},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0, .external_lex_state = 9},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0, .external_lex_state = 6},
  [144] = {.lex_state = 0, .external_lex_state = 9},
  [145] = {.lex_state = 1},
  [146] = {.lex_state = 1},
  [147] = {.lex_state = 0, .external_lex_state = 9},
  [148] = {.lex_state = 1},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0, .external_lex_state = 9},
};

enum {
  ts_external_token__name_ = 0,
  ts_external_token__indent_ = 1,
  ts_external_token__dedent_ = 2,
  ts_external_token__samedent_ = 3,
  ts_external_token__newline_ = 4,
  ts_external_token__line_ending_ = 5,
  ts_external_token__end_of_file_ = 6,
  ts_external_token__multiline_spacing_ = 7,
  ts_external_token__inline_spacing_ = 8,
  ts_external_token__error_ = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__name_] = sym__name_,
  [ts_external_token__indent_] = sym__indent_,
  [ts_external_token__dedent_] = sym__dedent_,
  [ts_external_token__samedent_] = sym__samedent_,
  [ts_external_token__newline_] = sym__newline_,
  [ts_external_token__line_ending_] = sym__line_ending_,
  [ts_external_token__end_of_file_] = sym__end_of_file_,
  [ts_external_token__multiline_spacing_] = sym__multiline_spacing_,
  [ts_external_token__inline_spacing_] = sym__inline_spacing_,
  [ts_external_token__error_] = sym__error_,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__name_] = true,
    [ts_external_token__indent_] = true,
    [ts_external_token__dedent_] = true,
    [ts_external_token__samedent_] = true,
    [ts_external_token__newline_] = true,
    [ts_external_token__line_ending_] = true,
    [ts_external_token__end_of_file_] = true,
    [ts_external_token__multiline_spacing_] = true,
    [ts_external_token__inline_spacing_] = true,
    [ts_external_token__error_] = true,
  },
  [2] = {
    [ts_external_token__name_] = true,
    [ts_external_token__line_ending_] = true,
    [ts_external_token__end_of_file_] = true,
  },
  [3] = {
    [ts_external_token__name_] = true,
  },
  [4] = {
    [ts_external_token__name_] = true,
    [ts_external_token__samedent_] = true,
    [ts_external_token__line_ending_] = true,
  },
  [5] = {
    [ts_external_token__line_ending_] = true,
    [ts_external_token__end_of_file_] = true,
  },
  [6] = {
    [ts_external_token__line_ending_] = true,
  },
  [7] = {
    [ts_external_token__end_of_file_] = true,
  },
  [8] = {
    [ts_external_token__indent_] = true,
  },
  [9] = {
    [ts_external_token__samedent_] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_assignment_operator] = ACTIONS(1),
    [aux_sym__inline_value_token1] = ACTIONS(1),
    [aux_sym__multiline_empty_token1] = ACTIONS(1),
    [aux_sym__inline_empty_token1] = ACTIONS(1),
    [aux_sym__integer_token1] = ACTIONS(1),
    [aux_sym__signed_integer_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__name_] = ACTIONS(1),
    [sym__indent_] = ACTIONS(1),
    [sym__dedent_] = ACTIONS(1),
    [sym__samedent_] = ACTIONS(1),
    [sym__newline_] = ACTIONS(1),
    [sym__line_ending_] = ACTIONS(1),
    [sym__end_of_file_] = ACTIONS(1),
    [sym__multiline_spacing_] = ACTIONS(1),
    [sym__inline_spacing_] = ACTIONS(1),
    [sym__error_] = ACTIONS(1),
  },
  [1] = {
    [sym_src] = STATE(149),
    [sym__line_ending] = STATE(2),
    [sym__end_of_file] = STATE(20),
    [sym__struct] = STATE(23),
    [sym_map] = STATE(23),
    [sym__multiline_map] = STATE(79),
    [sym__multiline_map_entry] = STATE(11),
    [sym__multiline_map_named_entry] = STATE(43),
    [sym_name] = STATE(146),
    [sym__inline_literal] = STATE(23),
    [sym__multiline_empty] = STATE(23),
    [sym__inline_empty] = STATE(23),
    [sym__inline_number] = STATE(23),
    [sym__signed_number] = STATE(78),
    [sym__unsigned_number] = STATE(78),
    [sym__integer] = STATE(39),
    [sym__signed_integer] = STATE(44),
    [sym__decimal] = STATE(77),
    [sym__signed_decimal] = STATE(76),
    [sym__inline_text] = STATE(23),
    [aux_sym_src_repeat1] = STATE(2),
    [aux_sym__multiline_empty_token1] = ACTIONS(3),
    [aux_sym__inline_empty_token1] = ACTIONS(5),
    [aux_sym__integer_token1] = ACTIONS(7),
    [aux_sym__signed_integer_token1] = ACTIONS(9),
    [aux_sym__inline_text_token1] = ACTIONS(11),
    [sym__name_] = ACTIONS(13),
    [sym__line_ending_] = ACTIONS(15),
    [sym__end_of_file_] = ACTIONS(17),
  },
  [2] = {
    [sym__line_ending] = STATE(9),
    [sym__end_of_file] = STATE(24),
    [sym__struct] = STATE(25),
    [sym_map] = STATE(25),
    [sym__multiline_map] = STATE(79),
    [sym__multiline_map_entry] = STATE(11),
    [sym__multiline_map_named_entry] = STATE(43),
    [sym_name] = STATE(146),
    [sym__inline_literal] = STATE(25),
    [sym__multiline_empty] = STATE(25),
    [sym__inline_empty] = STATE(25),
    [sym__inline_number] = STATE(25),
    [sym__signed_number] = STATE(78),
    [sym__unsigned_number] = STATE(78),
    [sym__integer] = STATE(39),
    [sym__signed_integer] = STATE(44),
    [sym__decimal] = STATE(77),
    [sym__signed_decimal] = STATE(76),
    [sym__inline_text] = STATE(25),
    [aux_sym_src_repeat1] = STATE(9),
    [aux_sym__multiline_empty_token1] = ACTIONS(3),
    [aux_sym__inline_empty_token1] = ACTIONS(5),
    [aux_sym__integer_token1] = ACTIONS(7),
    [aux_sym__signed_integer_token1] = ACTIONS(9),
    [aux_sym__inline_text_token1] = ACTIONS(11),
    [sym__name_] = ACTIONS(13),
    [sym__line_ending_] = ACTIONS(19),
    [sym__end_of_file_] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(21), 1,
      aux_sym__multiline_empty_token1,
    ACTIONS(23), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(25), 1,
      aux_sym__integer_token1,
    ACTIONS(27), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(29), 1,
      aux_sym__inline_text_token1,
    STATE(27), 1,
      sym__signed_integer,
    STATE(31), 1,
      sym__integer,
    STATE(35), 1,
      sym__signed_decimal,
    STATE(42), 1,
      sym__decimal,
    STATE(43), 1,
      sym__multiline_map_named_entry,
    STATE(48), 1,
      sym__multiline_empty,
    STATE(146), 1,
      sym_name,
    STATE(50), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(51), 2,
      sym__multiline_map,
      sym__multiline_map_entry,
    STATE(47), 6,
      sym_map,
      sym__multiline_literal,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [56] = 16,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(31), 1,
      aux_sym__multiline_empty_token1,
    ACTIONS(33), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(35), 1,
      aux_sym__integer_token1,
    ACTIONS(37), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(39), 1,
      aux_sym__inline_text_token1,
    STATE(34), 1,
      sym__signed_integer,
    STATE(37), 1,
      sym__integer,
    STATE(61), 1,
      sym__multiline_empty,
    STATE(71), 1,
      sym__decimal,
    STATE(73), 1,
      sym__signed_decimal,
    STATE(81), 1,
      sym__multiline_map_named_entry,
    STATE(148), 1,
      sym_name,
    STATE(58), 2,
      sym__multiline_map,
      sym__multiline_map_entry,
    STATE(69), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(62), 6,
      sym_map,
      sym__multiline_literal,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [112] = 17,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(41), 1,
      aux_sym__multiline_empty_token1,
    ACTIONS(43), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(45), 1,
      aux_sym__integer_token1,
    ACTIONS(47), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(49), 1,
      aux_sym__inline_text_token1,
    STATE(14), 1,
      sym__multiline_map_entry,
    STATE(81), 1,
      sym__multiline_map_named_entry,
    STATE(111), 1,
      sym__integer,
    STATE(112), 1,
      sym__signed_integer,
    STATE(114), 1,
      sym__signed_decimal,
    STATE(116), 1,
      sym__decimal,
    STATE(144), 1,
      sym__multiline_empty,
    STATE(148), 1,
      sym_name,
    STATE(150), 1,
      sym__multiline_map,
    STATE(117), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(147), 6,
      sym_map,
      sym__multiline_literal,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [170] = 10,
    ACTIONS(51), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(53), 1,
      aux_sym__integer_token1,
    ACTIONS(55), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(57), 1,
      aux_sym__inline_text_token1,
    STATE(103), 1,
      sym__signed_integer,
    STATE(104), 1,
      sym__integer,
    STATE(132), 1,
      sym__decimal,
    STATE(135), 1,
      sym__signed_decimal,
    STATE(130), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(90), 4,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [205] = 10,
    ACTIONS(51), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(53), 1,
      aux_sym__integer_token1,
    ACTIONS(55), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(57), 1,
      aux_sym__inline_text_token1,
    STATE(103), 1,
      sym__signed_integer,
    STATE(104), 1,
      sym__integer,
    STATE(132), 1,
      sym__decimal,
    STATE(135), 1,
      sym__signed_decimal,
    STATE(130), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(97), 4,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [240] = 10,
    ACTIONS(51), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(53), 1,
      aux_sym__integer_token1,
    ACTIONS(55), 1,
      aux_sym__signed_integer_token1,
    ACTIONS(57), 1,
      aux_sym__inline_text_token1,
    STATE(103), 1,
      sym__signed_integer,
    STATE(104), 1,
      sym__integer,
    STATE(132), 1,
      sym__decimal,
    STATE(135), 1,
      sym__signed_decimal,
    STATE(130), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(109), 4,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [275] = 4,
    ACTIONS(63), 1,
      sym__line_ending_,
    ACTIONS(61), 2,
      sym__name_,
      sym__end_of_file_,
    STATE(9), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
    ACTIONS(59), 5,
      aux_sym__multiline_empty_token1,
      aux_sym__inline_empty_token1,
      aux_sym__integer_token1,
      aux_sym__signed_integer_token1,
      aux_sym__inline_text_token1,
  [294] = 7,
    ACTIONS(13), 1,
      sym__name_,
    STATE(16), 1,
      aux_sym__multiline_map_repeat1,
    STATE(100), 1,
      sym__multiline_map_entry,
    STATE(107), 1,
      sym__line_ending,
    STATE(124), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(66), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [318] = 7,
    ACTIONS(13), 1,
      sym__name_,
    STATE(10), 1,
      aux_sym__multiline_map_repeat1,
    STATE(93), 1,
      sym__line_ending,
    STATE(100), 1,
      sym__multiline_map_entry,
    STATE(124), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(68), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [342] = 6,
    STATE(16), 1,
      aux_sym__multiline_map_repeat1,
    STATE(84), 1,
      sym__line_ending,
    STATE(100), 1,
      sym__multiline_map_entry,
    STATE(124), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(66), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [364] = 6,
    STATE(17), 1,
      aux_sym__multiline_map_repeat1,
    STATE(88), 1,
      sym__line_ending,
    STATE(101), 1,
      sym__multiline_map_entry,
    STATE(124), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(66), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [385] = 8,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(68), 1,
      sym__samedent_,
    ACTIONS(70), 1,
      sym__line_ending_,
    STATE(15), 1,
      aux_sym__multiline_map_repeat1,
    STATE(92), 1,
      sym__line_ending,
    STATE(101), 1,
      sym__multiline_map_entry,
    STATE(124), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
  [410] = 8,
    ACTIONS(13), 1,
      sym__name_,
    ACTIONS(66), 1,
      sym__samedent_,
    ACTIONS(72), 1,
      sym__line_ending_,
    STATE(17), 1,
      aux_sym__multiline_map_repeat1,
    STATE(91), 1,
      sym__line_ending,
    STATE(101), 1,
      sym__multiline_map_entry,
    STATE(124), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
  [435] = 6,
    ACTIONS(76), 1,
      sym__name_,
    STATE(16), 1,
      aux_sym__multiline_map_repeat1,
    STATE(100), 1,
      sym__multiline_map_entry,
    STATE(124), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(74), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [456] = 6,
    ACTIONS(76), 1,
      sym__name_,
    STATE(17), 1,
      aux_sym__multiline_map_repeat1,
    STATE(101), 1,
      sym__multiline_map_entry,
    STATE(124), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(74), 2,
      sym__samedent_,
      sym__line_ending_,
  [476] = 5,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    STATE(122), 1,
      sym__end_of_file,
    STATE(26), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [493] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(123), 1,
      sym__end_of_file,
    STATE(26), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [510] = 5,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 1,
      sym__line_ending_,
    STATE(142), 1,
      sym__end_of_file,
    STATE(21), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [527] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    STATE(129), 1,
      sym__end_of_file,
    STATE(26), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [544] = 5,
    ACTIONS(81), 1,
      sym__line_ending_,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    STATE(128), 1,
      sym__end_of_file,
    STATE(26), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [561] = 5,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(97), 1,
      sym__line_ending_,
    STATE(140), 1,
      sym__end_of_file,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [578] = 5,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      sym__line_ending_,
    STATE(125), 1,
      sym__end_of_file,
    STATE(19), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [595] = 5,
    ACTIONS(83), 1,
      sym__end_of_file_,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(103), 1,
      sym__line_ending_,
    STATE(128), 1,
      sym__end_of_file,
    STATE(18), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [612] = 3,
    ACTIONS(105), 1,
      sym__line_ending_,
    ACTIONS(61), 2,
      sym__end_of_file_,
      ts_builtin_sym_end,
    STATE(26), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [624] = 2,
    ACTIONS(110), 1,
      anon_sym_DOT,
    ACTIONS(108), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [634] = 4,
    ACTIONS(112), 1,
      aux_sym__inline_value_token1,
    ACTIONS(114), 1,
      sym__line_ending_,
    STATE(86), 1,
      sym__line_ending,
    STATE(66), 2,
      sym__inline_value,
      sym__child_value,
  [648] = 4,
    ACTIONS(116), 1,
      aux_sym__inline_value_token1,
    ACTIONS(118), 1,
      sym__line_ending_,
    STATE(87), 1,
      sym__line_ending,
    STATE(137), 2,
      sym__inline_value,
      sym__child_value,
  [662] = 4,
    ACTIONS(120), 1,
      aux_sym__inline_value_token1,
    ACTIONS(122), 1,
      sym__line_ending_,
    STATE(108), 1,
      sym__line_ending,
    STATE(41), 2,
      sym__inline_value,
      sym__child_value,
  [676] = 2,
    ACTIONS(126), 1,
      anon_sym_DOT,
    ACTIONS(124), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [686] = 1,
    ACTIONS(74), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [693] = 1,
    ACTIONS(128), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [700] = 2,
    ACTIONS(130), 1,
      anon_sym_DOT,
    ACTIONS(108), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [709] = 1,
    ACTIONS(108), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [716] = 1,
    ACTIONS(132), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [723] = 2,
    ACTIONS(134), 1,
      anon_sym_DOT,
    ACTIONS(124), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [732] = 1,
    ACTIONS(136), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [739] = 2,
    ACTIONS(138), 1,
      anon_sym_DOT,
    ACTIONS(124), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [748] = 1,
    ACTIONS(140), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [755] = 1,
    ACTIONS(142), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [762] = 1,
    ACTIONS(124), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [769] = 1,
    ACTIONS(144), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [776] = 2,
    ACTIONS(146), 1,
      anon_sym_DOT,
    ACTIONS(108), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [785] = 1,
    ACTIONS(148), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [792] = 1,
    ACTIONS(150), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [799] = 1,
    ACTIONS(152), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [806] = 1,
    ACTIONS(154), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [813] = 1,
    ACTIONS(156), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [820] = 1,
    ACTIONS(158), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [827] = 1,
    ACTIONS(160), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [834] = 1,
    ACTIONS(162), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [841] = 1,
    ACTIONS(164), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [848] = 1,
    ACTIONS(164), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [854] = 1,
    ACTIONS(140), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [860] = 1,
    ACTIONS(162), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [866] = 1,
    ACTIONS(132), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [872] = 1,
    ACTIONS(160), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [878] = 1,
    ACTIONS(128), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [884] = 1,
    ACTIONS(156), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [890] = 1,
    ACTIONS(154), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [896] = 1,
    ACTIONS(152), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [902] = 1,
    ACTIONS(150), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [908] = 1,
    ACTIONS(148), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [914] = 1,
    ACTIONS(128), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [920] = 1,
    ACTIONS(142), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [926] = 1,
    ACTIONS(136), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [932] = 1,
    ACTIONS(132), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [938] = 1,
    ACTIONS(158), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [944] = 1,
    ACTIONS(140), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [950] = 1,
    ACTIONS(124), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [956] = 1,
    ACTIONS(74), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [962] = 1,
    ACTIONS(108), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [968] = 1,
    ACTIONS(164), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [974] = 1,
    ACTIONS(162), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [980] = 1,
    ACTIONS(108), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [986] = 1,
    ACTIONS(124), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [992] = 1,
    ACTIONS(158), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [998] = 1,
    ACTIONS(160), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1004] = 1,
    ACTIONS(148), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1010] = 1,
    ACTIONS(144), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1016] = 1,
    ACTIONS(136), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1022] = 1,
    ACTIONS(156), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1028] = 2,
    ACTIONS(166), 1,
      sym__end_of_file_,
    STATE(33), 1,
      sym__end_of_file,
  [1035] = 2,
    ACTIONS(168), 1,
      aux_sym__integer_token1,
    STATE(54), 1,
      sym__integer,
  [1042] = 2,
    ACTIONS(170), 1,
      sym__indent_,
    STATE(4), 1,
      sym__increase_indent,
  [1049] = 2,
    ACTIONS(172), 1,
      sym__indent_,
    STATE(5), 1,
      sym__increase_indent,
  [1056] = 2,
    ACTIONS(174), 1,
      sym__end_of_file_,
    STATE(59), 1,
      sym__end_of_file,
  [1063] = 2,
    ACTIONS(174), 1,
      sym__end_of_file_,
    STATE(55), 1,
      sym__end_of_file,
  [1070] = 2,
    ACTIONS(176), 1,
      sym__line_ending_,
    STATE(63), 1,
      sym__line_ending,
  [1077] = 2,
    ACTIONS(178), 1,
      sym__end_of_file_,
    STATE(134), 1,
      sym__end_of_file,
  [1084] = 2,
    ACTIONS(178), 1,
      sym__end_of_file_,
    STATE(136), 1,
      sym__end_of_file,
  [1091] = 2,
    ACTIONS(17), 1,
      sym__end_of_file_,
    STATE(70), 1,
      sym__end_of_file,
  [1098] = 2,
    ACTIONS(180), 1,
      aux_sym__integer_token1,
    STATE(143), 1,
      sym__integer,
  [1105] = 2,
    ACTIONS(182), 1,
      aux_sym__integer_token1,
    STATE(53), 1,
      sym__integer,
  [1112] = 2,
    ACTIONS(184), 1,
      aux_sym__integer_token1,
    STATE(52), 1,
      sym__integer,
  [1119] = 2,
    ACTIONS(186), 1,
      sym__line_ending_,
    STATE(133), 1,
      sym__line_ending,
  [1126] = 2,
    ACTIONS(188), 1,
      aux_sym__integer_token1,
    STATE(139), 1,
      sym__integer,
  [1133] = 2,
    ACTIONS(166), 1,
      sym__end_of_file_,
    STATE(40), 1,
      sym__end_of_file,
  [1140] = 2,
    ACTIONS(190), 1,
      sym__samedent_,
    STATE(32), 1,
      sym__current_indent,
  [1147] = 2,
    ACTIONS(192), 1,
      sym__samedent_,
    STATE(72), 1,
      sym__current_indent,
  [1154] = 2,
    ACTIONS(194), 1,
      aux_sym__integer_token1,
    STATE(56), 1,
      sym__integer,
  [1161] = 2,
    ACTIONS(108), 1,
      sym__line_ending_,
    ACTIONS(196), 1,
      anon_sym_DOT,
  [1168] = 2,
    ACTIONS(124), 1,
      sym__line_ending_,
    ACTIONS(198), 1,
      anon_sym_DOT,
  [1175] = 2,
    ACTIONS(200), 1,
      aux_sym__integer_token1,
    STATE(75), 1,
      sym__integer,
  [1182] = 2,
    ACTIONS(202), 1,
      aux_sym__integer_token1,
    STATE(74), 1,
      sym__integer,
  [1189] = 2,
    ACTIONS(17), 1,
      sym__end_of_file_,
    STATE(65), 1,
      sym__end_of_file,
  [1196] = 2,
    ACTIONS(204), 1,
      sym__indent_,
    STATE(3), 1,
      sym__increase_indent,
  [1203] = 2,
    ACTIONS(206), 1,
      sym__line_ending_,
    STATE(46), 1,
      sym__line_ending,
  [1210] = 2,
    ACTIONS(208), 1,
      aux_sym__integer_token1,
    STATE(120), 1,
      sym__integer,
  [1217] = 2,
    ACTIONS(124), 1,
      sym__samedent_,
    ACTIONS(210), 1,
      anon_sym_DOT,
  [1224] = 2,
    ACTIONS(108), 1,
      sym__samedent_,
    ACTIONS(212), 1,
      anon_sym_DOT,
  [1231] = 2,
    ACTIONS(214), 1,
      aux_sym__integer_token1,
    STATE(119), 1,
      sym__integer,
  [1238] = 1,
    ACTIONS(108), 1,
      sym__samedent_,
  [1242] = 1,
    ACTIONS(148), 1,
      sym__line_ending_,
  [1246] = 1,
    ACTIONS(124), 1,
      sym__samedent_,
  [1250] = 1,
    ACTIONS(158), 1,
      sym__samedent_,
  [1254] = 1,
    ACTIONS(136), 1,
      sym__line_ending_,
  [1258] = 1,
    ACTIONS(164), 1,
      sym__samedent_,
  [1262] = 1,
    ACTIONS(162), 1,
      sym__samedent_,
  [1266] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [1270] = 1,
    ACTIONS(216), 1,
      ts_builtin_sym_end,
  [1274] = 1,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
  [1278] = 1,
    ACTIONS(144), 1,
      sym__samedent_,
  [1282] = 1,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [1286] = 1,
    ACTIONS(148), 1,
      sym__samedent_,
  [1290] = 1,
    ACTIONS(136), 1,
      sym__samedent_,
  [1294] = 1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
  [1298] = 1,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
  [1302] = 1,
    ACTIONS(158), 1,
      sym__line_ending_,
  [1306] = 1,
    ACTIONS(132), 1,
      sym__samedent_,
  [1310] = 1,
    ACTIONS(124), 1,
      sym__line_ending_,
  [1314] = 1,
    ACTIONS(150), 1,
      sym__samedent_,
  [1318] = 1,
    ACTIONS(128), 1,
      sym__samedent_,
  [1322] = 1,
    ACTIONS(108), 1,
      sym__line_ending_,
  [1326] = 1,
    ACTIONS(140), 1,
      sym__samedent_,
  [1330] = 1,
    ACTIONS(142), 1,
      sym__samedent_,
  [1334] = 1,
    ACTIONS(222), 1,
      sym_assignment_operator,
  [1338] = 1,
    ACTIONS(164), 1,
      sym__line_ending_,
  [1342] = 1,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
  [1346] = 1,
    ACTIONS(156), 1,
      sym__samedent_,
  [1350] = 1,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
  [1354] = 1,
    ACTIONS(162), 1,
      sym__line_ending_,
  [1358] = 1,
    ACTIONS(154), 1,
      sym__samedent_,
  [1362] = 1,
    ACTIONS(224), 1,
      sym_assignment_operator,
  [1366] = 1,
    ACTIONS(226), 1,
      sym_assignment_operator,
  [1370] = 1,
    ACTIONS(152), 1,
      sym__samedent_,
  [1374] = 1,
    ACTIONS(228), 1,
      sym_assignment_operator,
  [1378] = 1,
    ACTIONS(230), 1,
      ts_builtin_sym_end,
  [1382] = 1,
    ACTIONS(160), 1,
      sym__samedent_,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 112,
  [SMALL_STATE(6)] = 170,
  [SMALL_STATE(7)] = 205,
  [SMALL_STATE(8)] = 240,
  [SMALL_STATE(9)] = 275,
  [SMALL_STATE(10)] = 294,
  [SMALL_STATE(11)] = 318,
  [SMALL_STATE(12)] = 342,
  [SMALL_STATE(13)] = 364,
  [SMALL_STATE(14)] = 385,
  [SMALL_STATE(15)] = 410,
  [SMALL_STATE(16)] = 435,
  [SMALL_STATE(17)] = 456,
  [SMALL_STATE(18)] = 476,
  [SMALL_STATE(19)] = 493,
  [SMALL_STATE(20)] = 510,
  [SMALL_STATE(21)] = 527,
  [SMALL_STATE(22)] = 544,
  [SMALL_STATE(23)] = 561,
  [SMALL_STATE(24)] = 578,
  [SMALL_STATE(25)] = 595,
  [SMALL_STATE(26)] = 612,
  [SMALL_STATE(27)] = 624,
  [SMALL_STATE(28)] = 634,
  [SMALL_STATE(29)] = 648,
  [SMALL_STATE(30)] = 662,
  [SMALL_STATE(31)] = 676,
  [SMALL_STATE(32)] = 686,
  [SMALL_STATE(33)] = 693,
  [SMALL_STATE(34)] = 700,
  [SMALL_STATE(35)] = 709,
  [SMALL_STATE(36)] = 716,
  [SMALL_STATE(37)] = 723,
  [SMALL_STATE(38)] = 732,
  [SMALL_STATE(39)] = 739,
  [SMALL_STATE(40)] = 748,
  [SMALL_STATE(41)] = 755,
  [SMALL_STATE(42)] = 762,
  [SMALL_STATE(43)] = 769,
  [SMALL_STATE(44)] = 776,
  [SMALL_STATE(45)] = 785,
  [SMALL_STATE(46)] = 792,
  [SMALL_STATE(47)] = 799,
  [SMALL_STATE(48)] = 806,
  [SMALL_STATE(49)] = 813,
  [SMALL_STATE(50)] = 820,
  [SMALL_STATE(51)] = 827,
  [SMALL_STATE(52)] = 834,
  [SMALL_STATE(53)] = 841,
  [SMALL_STATE(54)] = 848,
  [SMALL_STATE(55)] = 854,
  [SMALL_STATE(56)] = 860,
  [SMALL_STATE(57)] = 866,
  [SMALL_STATE(58)] = 872,
  [SMALL_STATE(59)] = 878,
  [SMALL_STATE(60)] = 884,
  [SMALL_STATE(61)] = 890,
  [SMALL_STATE(62)] = 896,
  [SMALL_STATE(63)] = 902,
  [SMALL_STATE(64)] = 908,
  [SMALL_STATE(65)] = 914,
  [SMALL_STATE(66)] = 920,
  [SMALL_STATE(67)] = 926,
  [SMALL_STATE(68)] = 932,
  [SMALL_STATE(69)] = 938,
  [SMALL_STATE(70)] = 944,
  [SMALL_STATE(71)] = 950,
  [SMALL_STATE(72)] = 956,
  [SMALL_STATE(73)] = 962,
  [SMALL_STATE(74)] = 968,
  [SMALL_STATE(75)] = 974,
  [SMALL_STATE(76)] = 980,
  [SMALL_STATE(77)] = 986,
  [SMALL_STATE(78)] = 992,
  [SMALL_STATE(79)] = 998,
  [SMALL_STATE(80)] = 1004,
  [SMALL_STATE(81)] = 1010,
  [SMALL_STATE(82)] = 1016,
  [SMALL_STATE(83)] = 1022,
  [SMALL_STATE(84)] = 1028,
  [SMALL_STATE(85)] = 1035,
  [SMALL_STATE(86)] = 1042,
  [SMALL_STATE(87)] = 1049,
  [SMALL_STATE(88)] = 1056,
  [SMALL_STATE(89)] = 1063,
  [SMALL_STATE(90)] = 1070,
  [SMALL_STATE(91)] = 1077,
  [SMALL_STATE(92)] = 1084,
  [SMALL_STATE(93)] = 1091,
  [SMALL_STATE(94)] = 1098,
  [SMALL_STATE(95)] = 1105,
  [SMALL_STATE(96)] = 1112,
  [SMALL_STATE(97)] = 1119,
  [SMALL_STATE(98)] = 1126,
  [SMALL_STATE(99)] = 1133,
  [SMALL_STATE(100)] = 1140,
  [SMALL_STATE(101)] = 1147,
  [SMALL_STATE(102)] = 1154,
  [SMALL_STATE(103)] = 1161,
  [SMALL_STATE(104)] = 1168,
  [SMALL_STATE(105)] = 1175,
  [SMALL_STATE(106)] = 1182,
  [SMALL_STATE(107)] = 1189,
  [SMALL_STATE(108)] = 1196,
  [SMALL_STATE(109)] = 1203,
  [SMALL_STATE(110)] = 1210,
  [SMALL_STATE(111)] = 1217,
  [SMALL_STATE(112)] = 1224,
  [SMALL_STATE(113)] = 1231,
  [SMALL_STATE(114)] = 1238,
  [SMALL_STATE(115)] = 1242,
  [SMALL_STATE(116)] = 1246,
  [SMALL_STATE(117)] = 1250,
  [SMALL_STATE(118)] = 1254,
  [SMALL_STATE(119)] = 1258,
  [SMALL_STATE(120)] = 1262,
  [SMALL_STATE(121)] = 1266,
  [SMALL_STATE(122)] = 1270,
  [SMALL_STATE(123)] = 1274,
  [SMALL_STATE(124)] = 1278,
  [SMALL_STATE(125)] = 1282,
  [SMALL_STATE(126)] = 1286,
  [SMALL_STATE(127)] = 1290,
  [SMALL_STATE(128)] = 1294,
  [SMALL_STATE(129)] = 1298,
  [SMALL_STATE(130)] = 1302,
  [SMALL_STATE(131)] = 1306,
  [SMALL_STATE(132)] = 1310,
  [SMALL_STATE(133)] = 1314,
  [SMALL_STATE(134)] = 1318,
  [SMALL_STATE(135)] = 1322,
  [SMALL_STATE(136)] = 1326,
  [SMALL_STATE(137)] = 1330,
  [SMALL_STATE(138)] = 1334,
  [SMALL_STATE(139)] = 1338,
  [SMALL_STATE(140)] = 1342,
  [SMALL_STATE(141)] = 1346,
  [SMALL_STATE(142)] = 1350,
  [SMALL_STATE(143)] = 1354,
  [SMALL_STATE(144)] = 1358,
  [SMALL_STATE(145)] = 1362,
  [SMALL_STATE(146)] = 1366,
  [SMALL_STATE(147)] = 1370,
  [SMALL_STATE(148)] = 1374,
  [SMALL_STATE(149)] = 1378,
  [SMALL_STATE(150)] = 1382,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(141),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_src_repeat1, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_src_repeat1, 2),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_src_repeat1, 2), SHIFT_REPEAT(9),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 2),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_map_repeat1, 2),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiline_map_repeat1, 2), SHIFT_REPEAT(138),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 3, .production_id = 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 1, .production_id = 1),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 2, .production_id = 1),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 2),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 2, .production_id = 3),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_src_repeat1, 2), SHIFT_REPEAT(26),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__signed_number, 1),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unsigned_number, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 4),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_of_file, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_empty, 1),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 3),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map_named_entry, 3, .production_id = 4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map_entry, 1, .production_id = 2),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_text, 1),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_value, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__child_value, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_literal, 1, .production_id = 5),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_empty, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_number, 1),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__signed_decimal, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 4),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 4, .production_id = 3),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 3, .production_id = 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [230] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_strux_external_scanner_create(void);
void tree_sitter_strux_external_scanner_destroy(void *);
bool tree_sitter_strux_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_strux_external_scanner_serialize(void *, char *);
void tree_sitter_strux_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_strux(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_strux_external_scanner_create,
      tree_sitter_strux_external_scanner_destroy,
      tree_sitter_strux_external_scanner_scan,
      tree_sitter_strux_external_scanner_serialize,
      tree_sitter_strux_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
