#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 151
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 18
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 6

enum {
  sym_assignment_operator = 1,
  aux_sym__inline_value_token1 = 2,
  aux_sym__multiline_empty_token1 = 3,
  aux_sym__inline_empty_token1 = 4,
  aux_sym__integer_token1 = 5,
  anon_sym_DOT = 6,
  aux_sym__inline_text_token1 = 7,
  sym__name_ = 8,
  sym__indent_ = 9,
  sym__dedent_ = 10,
  sym__samedent_ = 11,
  sym__newline_ = 12,
  sym__line_ending_ = 13,
  sym__end_of_file_ = 14,
  sym__multiline_spacing_ = 15,
  sym__inline_spacing_ = 16,
  sym__error_ = 17,
  sym_src = 18,
  sym__current_indent = 19,
  sym__increase_indent = 20,
  sym__line_ending = 21,
  sym__end_of_file = 22,
  sym__struct = 23,
  sym_map = 24,
  sym__multiline_map = 25,
  sym__multiline_map_entry = 26,
  sym__multiline_map_named_entry = 27,
  sym_name = 28,
  sym__inline_value = 29,
  sym__child_value = 30,
  sym__multiline_literal = 31,
  sym__inline_literal = 32,
  sym__multiline_empty = 33,
  sym__inline_empty = 34,
  sym__inline_number = 35,
  sym__signed_number = 36,
  sym__unsigned_number = 37,
  sym__integer = 38,
  sym__signed_integer = 39,
  sym__decimal = 40,
  sym__signed_decimal = 41,
  sym__inline_text = 42,
  aux_sym_src_repeat1 = 43,
  aux_sym__multiline_map_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_assignment_operator] = "assignment_operator",
  [aux_sym__inline_value_token1] = "_inline_value_token1",
  [aux_sym__multiline_empty_token1] = "empty",
  [aux_sym__inline_empty_token1] = "empty",
  [aux_sym__integer_token1] = "integer",
  [anon_sym_DOT] = ".",
  [aux_sym__inline_text_token1] = "text",
  [sym__name_] = "_name_",
  [sym__indent_] = "_indent_",
  [sym__dedent_] = "_dedent_",
  [sym__samedent_] = "_samedent_",
  [sym__newline_] = "_newline_",
  [sym__line_ending_] = "_line_ending_",
  [sym__end_of_file_] = "_end_of_file_",
  [sym__multiline_spacing_] = "_multiline_spacing_",
  [sym__inline_spacing_] = "_inline_spacing_",
  [sym__error_] = "_error_",
  [sym_src] = "src",
  [sym__current_indent] = "_current_indent",
  [sym__increase_indent] = "_increase_indent",
  [sym__line_ending] = "_line_ending",
  [sym__end_of_file] = "_end_of_file",
  [sym__struct] = "_struct",
  [sym_map] = "map",
  [sym__multiline_map] = "_multiline_map",
  [sym__multiline_map_entry] = "_multiline_map_entry",
  [sym__multiline_map_named_entry] = "named_entry",
  [sym_name] = "name",
  [sym__inline_value] = "_inline_value",
  [sym__child_value] = "_child_value",
  [sym__multiline_literal] = "_multiline_literal",
  [sym__inline_literal] = "_inline_literal",
  [sym__multiline_empty] = "_multiline_empty",
  [sym__inline_empty] = "literal",
  [sym__inline_number] = "literal",
  [sym__signed_number] = "number",
  [sym__unsigned_number] = "number",
  [sym__integer] = "_integer",
  [sym__signed_integer] = "_signed_integer",
  [sym__decimal] = "_decimal",
  [sym__signed_decimal] = "_signed_decimal",
  [sym__inline_text] = "literal",
  [aux_sym_src_repeat1] = "src_repeat1",
  [aux_sym__multiline_map_repeat1] = "_multiline_map_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_assignment_operator] = sym_assignment_operator,
  [aux_sym__inline_value_token1] = aux_sym__inline_value_token1,
  [aux_sym__multiline_empty_token1] = aux_sym__multiline_empty_token1,
  [aux_sym__inline_empty_token1] = aux_sym__multiline_empty_token1,
  [aux_sym__integer_token1] = aux_sym__integer_token1,
  [anon_sym_DOT] = anon_sym_DOT,
  [aux_sym__inline_text_token1] = aux_sym__inline_text_token1,
  [sym__name_] = sym__name_,
  [sym__indent_] = sym__indent_,
  [sym__dedent_] = sym__dedent_,
  [sym__samedent_] = sym__samedent_,
  [sym__newline_] = sym__newline_,
  [sym__line_ending_] = sym__line_ending_,
  [sym__end_of_file_] = sym__end_of_file_,
  [sym__multiline_spacing_] = sym__multiline_spacing_,
  [sym__inline_spacing_] = sym__inline_spacing_,
  [sym__error_] = sym__error_,
  [sym_src] = sym_src,
  [sym__current_indent] = sym__current_indent,
  [sym__increase_indent] = sym__increase_indent,
  [sym__line_ending] = sym__line_ending,
  [sym__end_of_file] = sym__end_of_file,
  [sym__struct] = sym__struct,
  [sym_map] = sym_map,
  [sym__multiline_map] = sym__multiline_map,
  [sym__multiline_map_entry] = sym__multiline_map_entry,
  [sym__multiline_map_named_entry] = sym__multiline_map_named_entry,
  [sym_name] = sym_name,
  [sym__inline_value] = sym__inline_value,
  [sym__child_value] = sym__child_value,
  [sym__multiline_literal] = sym__multiline_literal,
  [sym__inline_literal] = sym__inline_literal,
  [sym__multiline_empty] = sym__multiline_empty,
  [sym__inline_empty] = sym__inline_empty,
  [sym__inline_number] = sym__inline_empty,
  [sym__signed_number] = sym__signed_number,
  [sym__unsigned_number] = sym__signed_number,
  [sym__integer] = sym__integer,
  [sym__signed_integer] = sym__signed_integer,
  [sym__decimal] = sym__decimal,
  [sym__signed_decimal] = sym__signed_decimal,
  [sym__inline_text] = sym__inline_empty,
  [aux_sym_src_repeat1] = aux_sym_src_repeat1,
  [aux_sym__multiline_map_repeat1] = aux_sym__multiline_map_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_assignment_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline_value_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__multiline_empty_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__inline_empty_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__integer_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__inline_text_token1] = {
    .visible = true,
    .named = true,
  },
  [sym__name_] = {
    .visible = false,
    .named = true,
  },
  [sym__indent_] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent_] = {
    .visible = false,
    .named = true,
  },
  [sym__samedent_] = {
    .visible = false,
    .named = true,
  },
  [sym__newline_] = {
    .visible = false,
    .named = true,
  },
  [sym__line_ending_] = {
    .visible = false,
    .named = true,
  },
  [sym__end_of_file_] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_spacing_] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_spacing_] = {
    .visible = false,
    .named = true,
  },
  [sym__error_] = {
    .visible = false,
    .named = true,
  },
  [sym_src] = {
    .visible = true,
    .named = true,
  },
  [sym__current_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__increase_indent] = {
    .visible = false,
    .named = true,
  },
  [sym__line_ending] = {
    .visible = false,
    .named = true,
  },
  [sym__end_of_file] = {
    .visible = false,
    .named = true,
  },
  [sym__struct] = {
    .visible = false,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym__multiline_map] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_map_entry] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_map_named_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_value] = {
    .visible = false,
    .named = true,
  },
  [sym__child_value] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_literal] = {
    .visible = false,
    .named = true,
  },
  [sym__multiline_empty] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_empty] = {
    .visible = true,
    .named = true,
  },
  [sym__inline_number] = {
    .visible = true,
    .named = true,
  },
  [sym__signed_number] = {
    .visible = true,
    .named = true,
  },
  [sym__unsigned_number] = {
    .visible = true,
    .named = true,
  },
  [sym__integer] = {
    .visible = false,
    .named = true,
  },
  [sym__signed_integer] = {
    .visible = false,
    .named = true,
  },
  [sym__decimal] = {
    .visible = false,
    .named = true,
  },
  [sym__signed_decimal] = {
    .visible = false,
    .named = true,
  },
  [sym__inline_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_src_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__multiline_map_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_operator = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_operator] = "operator",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 3},
  [4] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0, .inherited = true},
    {field_operator, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [3] =
    {field_key, 0},
    {field_operator, 1},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = aux_sym__multiline_empty_token1,
  },
  [3] = {
    [1] = aux_sym__multiline_empty_token1,
  },
  [5] = {
    [0] = sym__inline_empty,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym__end_of_file, 2,
    sym__end_of_file,
    aux_sym__multiline_empty_token1,
  sym__multiline_empty, 2,
    sym__multiline_empty,
    sym__inline_empty,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 3,
  [6] = 6,
  [7] = 6,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 9,
  [16] = 9,
  [17] = 14,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 26,
  [28] = 28,
  [29] = 29,
  [30] = 26,
  [31] = 10,
  [32] = 28,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 29,
  [46] = 29,
  [47] = 47,
  [48] = 28,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 33,
  [55] = 49,
  [56] = 43,
  [57] = 42,
  [58] = 43,
  [59] = 40,
  [60] = 35,
  [61] = 44,
  [62] = 37,
  [63] = 40,
  [64] = 42,
  [65] = 49,
  [66] = 51,
  [67] = 50,
  [68] = 44,
  [69] = 33,
  [70] = 51,
  [71] = 36,
  [72] = 39,
  [73] = 37,
  [74] = 53,
  [75] = 52,
  [76] = 34,
  [77] = 35,
  [78] = 38,
  [79] = 38,
  [80] = 34,
  [81] = 41,
  [82] = 50,
  [83] = 47,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 87,
  [90] = 88,
  [91] = 91,
  [92] = 84,
  [93] = 93,
  [94] = 85,
  [95] = 91,
  [96] = 84,
  [97] = 93,
  [98] = 88,
  [99] = 87,
  [100] = 86,
  [101] = 93,
  [102] = 84,
  [103] = 93,
  [104] = 29,
  [105] = 28,
  [106] = 28,
  [107] = 29,
  [108] = 88,
  [109] = 87,
  [110] = 88,
  [111] = 87,
  [112] = 85,
  [113] = 86,
  [114] = 53,
  [115] = 37,
  [116] = 49,
  [117] = 51,
  [118] = 43,
  [119] = 35,
  [120] = 34,
  [121] = 121,
  [122] = 38,
  [123] = 123,
  [124] = 40,
  [125] = 42,
  [126] = 126,
  [127] = 127,
  [128] = 33,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 50,
  [133] = 44,
  [134] = 39,
  [135] = 52,
  [136] = 136,
  [137] = 38,
  [138] = 34,
  [139] = 41,
  [140] = 51,
  [141] = 49,
  [142] = 43,
  [143] = 47,
  [144] = 35,
  [145] = 121,
  [146] = 37,
  [147] = 40,
  [148] = 121,
  [149] = 149,
  [150] = 150,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (eof) ADVANCE(3);
      if (lookahead == '-') ADVANCE(1);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 1:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 2:
      if (eof) ADVANCE(3);
      if (lookahead == '.') ADVANCE(14);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_assignment_operator);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym__inline_value_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(8);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(9);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym__multiline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__inline_empty_token1);
      if (lookahead == '-') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym__inline_empty_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(11);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym__integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym__inline_text_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym__inline_text_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 6, .external_lex_state = 2},
  [2] = {.lex_state = 6, .external_lex_state = 2},
  [3] = {.lex_state = 6, .external_lex_state = 3},
  [4] = {.lex_state = 6, .external_lex_state = 3},
  [5] = {.lex_state = 6, .external_lex_state = 3},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 6, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 4},
  [14] = {.lex_state = 0, .external_lex_state = 2},
  [15] = {.lex_state = 0, .external_lex_state = 4},
  [16] = {.lex_state = 0, .external_lex_state = 4},
  [17] = {.lex_state = 0, .external_lex_state = 4},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 5},
  [21] = {.lex_state = 0, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 5},
  [23] = {.lex_state = 0, .external_lex_state = 5},
  [24] = {.lex_state = 0, .external_lex_state = 5},
  [25] = {.lex_state = 0, .external_lex_state = 5},
  [26] = {.lex_state = 2, .external_lex_state = 6},
  [27] = {.lex_state = 2, .external_lex_state = 6},
  [28] = {.lex_state = 2, .external_lex_state = 2},
  [29] = {.lex_state = 2, .external_lex_state = 2},
  [30] = {.lex_state = 2, .external_lex_state = 6},
  [31] = {.lex_state = 0, .external_lex_state = 5},
  [32] = {.lex_state = 2, .external_lex_state = 5},
  [33] = {.lex_state = 0, .external_lex_state = 2},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 2},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 2},
  [41] = {.lex_state = 0, .external_lex_state = 2},
  [42] = {.lex_state = 0, .external_lex_state = 2},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 2},
  [45] = {.lex_state = 2, .external_lex_state = 5},
  [46] = {.lex_state = 2, .external_lex_state = 4},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 2, .external_lex_state = 4},
  [49] = {.lex_state = 0, .external_lex_state = 2},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 2},
  [52] = {.lex_state = 0, .external_lex_state = 2},
  [53] = {.lex_state = 0, .external_lex_state = 2},
  [54] = {.lex_state = 0, .external_lex_state = 4},
  [55] = {.lex_state = 0, .external_lex_state = 4},
  [56] = {.lex_state = 0, .external_lex_state = 5},
  [57] = {.lex_state = 0, .external_lex_state = 5},
  [58] = {.lex_state = 0, .external_lex_state = 4},
  [59] = {.lex_state = 0, .external_lex_state = 5},
  [60] = {.lex_state = 0, .external_lex_state = 4},
  [61] = {.lex_state = 0, .external_lex_state = 5},
  [62] = {.lex_state = 0, .external_lex_state = 4},
  [63] = {.lex_state = 0, .external_lex_state = 4},
  [64] = {.lex_state = 0, .external_lex_state = 4},
  [65] = {.lex_state = 0, .external_lex_state = 5},
  [66] = {.lex_state = 0, .external_lex_state = 5},
  [67] = {.lex_state = 0, .external_lex_state = 4},
  [68] = {.lex_state = 0, .external_lex_state = 4},
  [69] = {.lex_state = 0, .external_lex_state = 5},
  [70] = {.lex_state = 0, .external_lex_state = 4},
  [71] = {.lex_state = 0, .external_lex_state = 4},
  [72] = {.lex_state = 0, .external_lex_state = 4},
  [73] = {.lex_state = 0, .external_lex_state = 5},
  [74] = {.lex_state = 0, .external_lex_state = 4},
  [75] = {.lex_state = 0, .external_lex_state = 4},
  [76] = {.lex_state = 0, .external_lex_state = 4},
  [77] = {.lex_state = 0, .external_lex_state = 5},
  [78] = {.lex_state = 0, .external_lex_state = 5},
  [79] = {.lex_state = 0, .external_lex_state = 4},
  [80] = {.lex_state = 0, .external_lex_state = 5},
  [81] = {.lex_state = 0, .external_lex_state = 4},
  [82] = {.lex_state = 0, .external_lex_state = 5},
  [83] = {.lex_state = 0, .external_lex_state = 4},
  [84] = {.lex_state = 0, .external_lex_state = 7},
  [85] = {.lex_state = 0, .external_lex_state = 8},
  [86] = {.lex_state = 0, .external_lex_state = 6},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0, .external_lex_state = 9},
  [92] = {.lex_state = 0, .external_lex_state = 7},
  [93] = {.lex_state = 0, .external_lex_state = 7},
  [94] = {.lex_state = 0, .external_lex_state = 8},
  [95] = {.lex_state = 0, .external_lex_state = 9},
  [96] = {.lex_state = 0, .external_lex_state = 7},
  [97] = {.lex_state = 0, .external_lex_state = 7},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0, .external_lex_state = 6},
  [101] = {.lex_state = 0, .external_lex_state = 7},
  [102] = {.lex_state = 0, .external_lex_state = 7},
  [103] = {.lex_state = 0, .external_lex_state = 7},
  [104] = {.lex_state = 2, .external_lex_state = 9},
  [105] = {.lex_state = 2, .external_lex_state = 9},
  [106] = {.lex_state = 2, .external_lex_state = 6},
  [107] = {.lex_state = 2, .external_lex_state = 6},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0, .external_lex_state = 8},
  [113] = {.lex_state = 0, .external_lex_state = 6},
  [114] = {.lex_state = 0, .external_lex_state = 9},
  [115] = {.lex_state = 0, .external_lex_state = 9},
  [116] = {.lex_state = 0, .external_lex_state = 9},
  [117] = {.lex_state = 0, .external_lex_state = 9},
  [118] = {.lex_state = 0, .external_lex_state = 9},
  [119] = {.lex_state = 0, .external_lex_state = 9},
  [120] = {.lex_state = 0, .external_lex_state = 9},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 0, .external_lex_state = 9},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0, .external_lex_state = 9},
  [125] = {.lex_state = 0, .external_lex_state = 9},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0, .external_lex_state = 9},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0, .external_lex_state = 9},
  [133] = {.lex_state = 0, .external_lex_state = 9},
  [134] = {.lex_state = 0, .external_lex_state = 9},
  [135] = {.lex_state = 0, .external_lex_state = 9},
  [136] = {.lex_state = 2},
  [137] = {.lex_state = 0, .external_lex_state = 6},
  [138] = {.lex_state = 0, .external_lex_state = 6},
  [139] = {.lex_state = 0, .external_lex_state = 9},
  [140] = {.lex_state = 0, .external_lex_state = 6},
  [141] = {.lex_state = 0, .external_lex_state = 6},
  [142] = {.lex_state = 0, .external_lex_state = 6},
  [143] = {.lex_state = 0, .external_lex_state = 9},
  [144] = {.lex_state = 0, .external_lex_state = 6},
  [145] = {.lex_state = 2},
  [146] = {.lex_state = 0, .external_lex_state = 6},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 2},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
};

enum {
  ts_external_token__name_ = 0,
  ts_external_token__indent_ = 1,
  ts_external_token__dedent_ = 2,
  ts_external_token__samedent_ = 3,
  ts_external_token__newline_ = 4,
  ts_external_token__line_ending_ = 5,
  ts_external_token__end_of_file_ = 6,
  ts_external_token__multiline_spacing_ = 7,
  ts_external_token__inline_spacing_ = 8,
  ts_external_token__error_ = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__name_] = sym__name_,
  [ts_external_token__indent_] = sym__indent_,
  [ts_external_token__dedent_] = sym__dedent_,
  [ts_external_token__samedent_] = sym__samedent_,
  [ts_external_token__newline_] = sym__newline_,
  [ts_external_token__line_ending_] = sym__line_ending_,
  [ts_external_token__end_of_file_] = sym__end_of_file_,
  [ts_external_token__multiline_spacing_] = sym__multiline_spacing_,
  [ts_external_token__inline_spacing_] = sym__inline_spacing_,
  [ts_external_token__error_] = sym__error_,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__name_] = true,
    [ts_external_token__indent_] = true,
    [ts_external_token__dedent_] = true,
    [ts_external_token__samedent_] = true,
    [ts_external_token__newline_] = true,
    [ts_external_token__line_ending_] = true,
    [ts_external_token__end_of_file_] = true,
    [ts_external_token__multiline_spacing_] = true,
    [ts_external_token__inline_spacing_] = true,
    [ts_external_token__error_] = true,
  },
  [2] = {
    [ts_external_token__name_] = true,
    [ts_external_token__line_ending_] = true,
    [ts_external_token__end_of_file_] = true,
  },
  [3] = {
    [ts_external_token__name_] = true,
  },
  [4] = {
    [ts_external_token__name_] = true,
    [ts_external_token__samedent_] = true,
    [ts_external_token__line_ending_] = true,
  },
  [5] = {
    [ts_external_token__line_ending_] = true,
    [ts_external_token__end_of_file_] = true,
  },
  [6] = {
    [ts_external_token__line_ending_] = true,
  },
  [7] = {
    [ts_external_token__end_of_file_] = true,
  },
  [8] = {
    [ts_external_token__indent_] = true,
  },
  [9] = {
    [ts_external_token__samedent_] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_assignment_operator] = ACTIONS(1),
    [aux_sym__inline_value_token1] = ACTIONS(1),
    [aux_sym__multiline_empty_token1] = ACTIONS(1),
    [aux_sym__inline_empty_token1] = ACTIONS(1),
    [aux_sym__integer_token1] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym__name_] = ACTIONS(1),
    [sym__indent_] = ACTIONS(1),
    [sym__dedent_] = ACTIONS(1),
    [sym__samedent_] = ACTIONS(1),
    [sym__newline_] = ACTIONS(1),
    [sym__line_ending_] = ACTIONS(1),
    [sym__end_of_file_] = ACTIONS(1),
    [sym__multiline_spacing_] = ACTIONS(1),
    [sym__inline_spacing_] = ACTIONS(1),
    [sym__error_] = ACTIONS(1),
  },
  [1] = {
    [sym_src] = STATE(131),
    [sym__line_ending] = STATE(2),
    [sym__end_of_file] = STATE(18),
    [sym__struct] = STATE(21),
    [sym_map] = STATE(21),
    [sym__multiline_map] = STATE(82),
    [sym__multiline_map_entry] = STATE(12),
    [sym__multiline_map_named_entry] = STATE(47),
    [sym_name] = STATE(121),
    [sym__inline_literal] = STATE(21),
    [sym__multiline_empty] = STATE(21),
    [sym__inline_empty] = STATE(21),
    [sym__inline_number] = STATE(21),
    [sym__signed_number] = STATE(56),
    [sym__unsigned_number] = STATE(56),
    [sym__integer] = STATE(45),
    [sym__signed_integer] = STATE(32),
    [sym__decimal] = STATE(65),
    [sym__signed_decimal] = STATE(66),
    [sym__inline_text] = STATE(21),
    [aux_sym_src_repeat1] = STATE(2),
    [aux_sym__multiline_empty_token1] = ACTIONS(3),
    [aux_sym__inline_empty_token1] = ACTIONS(5),
    [aux_sym__integer_token1] = ACTIONS(7),
    [aux_sym__inline_text_token1] = ACTIONS(9),
    [sym__name_] = ACTIONS(11),
    [sym__line_ending_] = ACTIONS(13),
    [sym__end_of_file_] = ACTIONS(15),
  },
  [2] = {
    [sym__line_ending] = STATE(10),
    [sym__end_of_file] = STATE(25),
    [sym__struct] = STATE(24),
    [sym_map] = STATE(24),
    [sym__multiline_map] = STATE(82),
    [sym__multiline_map_entry] = STATE(12),
    [sym__multiline_map_named_entry] = STATE(47),
    [sym_name] = STATE(121),
    [sym__inline_literal] = STATE(24),
    [sym__multiline_empty] = STATE(24),
    [sym__inline_empty] = STATE(24),
    [sym__inline_number] = STATE(24),
    [sym__signed_number] = STATE(56),
    [sym__unsigned_number] = STATE(56),
    [sym__integer] = STATE(45),
    [sym__signed_integer] = STATE(32),
    [sym__decimal] = STATE(65),
    [sym__signed_decimal] = STATE(66),
    [sym__inline_text] = STATE(24),
    [aux_sym_src_repeat1] = STATE(10),
    [aux_sym__multiline_empty_token1] = ACTIONS(3),
    [aux_sym__inline_empty_token1] = ACTIONS(5),
    [aux_sym__integer_token1] = ACTIONS(7),
    [aux_sym__inline_text_token1] = ACTIONS(9),
    [sym__name_] = ACTIONS(11),
    [sym__line_ending_] = ACTIONS(17),
    [sym__end_of_file_] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(11), 1,
      sym__name_,
    ACTIONS(19), 1,
      aux_sym__multiline_empty_token1,
    ACTIONS(21), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(23), 1,
      aux_sym__integer_token1,
    ACTIONS(25), 1,
      aux_sym__inline_text_token1,
    STATE(46), 1,
      sym__integer,
    STATE(48), 1,
      sym__signed_integer,
    STATE(55), 1,
      sym__decimal,
    STATE(70), 1,
      sym__signed_decimal,
    STATE(72), 1,
      sym__multiline_empty,
    STATE(83), 1,
      sym__multiline_map_named_entry,
    STATE(148), 1,
      sym_name,
    STATE(58), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(67), 2,
      sym__multiline_map,
      sym__multiline_map_entry,
    STATE(74), 6,
      sym_map,
      sym__multiline_literal,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [53] = 15,
    ACTIONS(11), 1,
      sym__name_,
    ACTIONS(27), 1,
      aux_sym__multiline_empty_token1,
    ACTIONS(29), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(31), 1,
      aux_sym__integer_token1,
    ACTIONS(33), 1,
      aux_sym__inline_text_token1,
    STATE(28), 1,
      sym__signed_integer,
    STATE(29), 1,
      sym__integer,
    STATE(39), 1,
      sym__multiline_empty,
    STATE(47), 1,
      sym__multiline_map_named_entry,
    STATE(49), 1,
      sym__decimal,
    STATE(51), 1,
      sym__signed_decimal,
    STATE(121), 1,
      sym_name,
    STATE(43), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(50), 2,
      sym__multiline_map,
      sym__multiline_map_entry,
    STATE(53), 6,
      sym_map,
      sym__multiline_literal,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [106] = 16,
    ACTIONS(11), 1,
      sym__name_,
    ACTIONS(35), 1,
      aux_sym__multiline_empty_token1,
    ACTIONS(37), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(39), 1,
      aux_sym__integer_token1,
    ACTIONS(41), 1,
      aux_sym__inline_text_token1,
    STATE(13), 1,
      sym__multiline_map_entry,
    STATE(83), 1,
      sym__multiline_map_named_entry,
    STATE(104), 1,
      sym__integer,
    STATE(105), 1,
      sym__signed_integer,
    STATE(116), 1,
      sym__decimal,
    STATE(117), 1,
      sym__signed_decimal,
    STATE(132), 1,
      sym__multiline_map,
    STATE(134), 1,
      sym__multiline_empty,
    STATE(148), 1,
      sym_name,
    STATE(118), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(114), 6,
      sym_map,
      sym__multiline_literal,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [161] = 9,
    ACTIONS(43), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(45), 1,
      aux_sym__integer_token1,
    ACTIONS(47), 1,
      aux_sym__inline_text_token1,
    STATE(106), 1,
      sym__signed_integer,
    STATE(107), 1,
      sym__integer,
    STATE(140), 1,
      sym__signed_decimal,
    STATE(141), 1,
      sym__decimal,
    STATE(142), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(100), 4,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [193] = 9,
    ACTIONS(43), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(45), 1,
      aux_sym__integer_token1,
    ACTIONS(47), 1,
      aux_sym__inline_text_token1,
    STATE(106), 1,
      sym__signed_integer,
    STATE(107), 1,
      sym__integer,
    STATE(140), 1,
      sym__signed_decimal,
    STATE(141), 1,
      sym__decimal,
    STATE(142), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(86), 4,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [225] = 9,
    ACTIONS(43), 1,
      aux_sym__inline_empty_token1,
    ACTIONS(45), 1,
      aux_sym__integer_token1,
    ACTIONS(47), 1,
      aux_sym__inline_text_token1,
    STATE(106), 1,
      sym__signed_integer,
    STATE(107), 1,
      sym__integer,
    STATE(140), 1,
      sym__signed_decimal,
    STATE(141), 1,
      sym__decimal,
    STATE(142), 2,
      sym__signed_number,
      sym__unsigned_number,
    STATE(113), 4,
      sym__inline_literal,
      sym__inline_empty,
      sym__inline_number,
      sym__inline_text,
  [257] = 6,
    STATE(14), 1,
      aux_sym__multiline_map_repeat1,
    STATE(91), 1,
      sym__multiline_map_entry,
    STATE(101), 1,
      sym__line_ending,
    STATE(143), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(49), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [279] = 4,
    ACTIONS(55), 1,
      sym__line_ending_,
    ACTIONS(53), 2,
      sym__name_,
      sym__end_of_file_,
    STATE(10), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
    ACTIONS(51), 4,
      aux_sym__multiline_empty_token1,
      aux_sym__inline_empty_token1,
      aux_sym__integer_token1,
      aux_sym__inline_text_token1,
  [297] = 7,
    ACTIONS(11), 1,
      sym__name_,
    STATE(14), 1,
      aux_sym__multiline_map_repeat1,
    STATE(91), 1,
      sym__multiline_map_entry,
    STATE(93), 1,
      sym__line_ending,
    STATE(143), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(49), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [321] = 7,
    ACTIONS(11), 1,
      sym__name_,
    STATE(11), 1,
      aux_sym__multiline_map_repeat1,
    STATE(91), 1,
      sym__multiline_map_entry,
    STATE(92), 1,
      sym__line_ending,
    STATE(143), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(58), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [345] = 8,
    ACTIONS(11), 1,
      sym__name_,
    ACTIONS(58), 1,
      sym__samedent_,
    ACTIONS(60), 1,
      sym__line_ending_,
    STATE(16), 1,
      aux_sym__multiline_map_repeat1,
    STATE(95), 1,
      sym__multiline_map_entry,
    STATE(96), 1,
      sym__line_ending,
    STATE(143), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
  [370] = 6,
    ACTIONS(64), 1,
      sym__name_,
    STATE(14), 1,
      aux_sym__multiline_map_repeat1,
    STATE(91), 1,
      sym__multiline_map_entry,
    STATE(143), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(62), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [391] = 6,
    STATE(17), 1,
      aux_sym__multiline_map_repeat1,
    STATE(95), 1,
      sym__multiline_map_entry,
    STATE(103), 1,
      sym__line_ending,
    STATE(143), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(49), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [412] = 8,
    ACTIONS(11), 1,
      sym__name_,
    ACTIONS(49), 1,
      sym__samedent_,
    ACTIONS(67), 1,
      sym__line_ending_,
    STATE(17), 1,
      aux_sym__multiline_map_repeat1,
    STATE(95), 1,
      sym__multiline_map_entry,
    STATE(97), 1,
      sym__line_ending,
    STATE(143), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
  [437] = 6,
    ACTIONS(64), 1,
      sym__name_,
    STATE(17), 1,
      aux_sym__multiline_map_repeat1,
    STATE(95), 1,
      sym__multiline_map_entry,
    STATE(143), 1,
      sym__multiline_map_named_entry,
    STATE(145), 1,
      sym_name,
    ACTIONS(62), 2,
      sym__samedent_,
      sym__line_ending_,
  [457] = 5,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      sym__line_ending_,
    ACTIONS(73), 1,
      sym__end_of_file_,
    STATE(126), 1,
      sym__end_of_file,
    STATE(22), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [474] = 5,
    ACTIONS(73), 1,
      sym__end_of_file_,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      sym__line_ending_,
    STATE(150), 1,
      sym__end_of_file,
    STATE(31), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [491] = 5,
    ACTIONS(73), 1,
      sym__end_of_file_,
    ACTIONS(77), 1,
      sym__line_ending_,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(149), 1,
      sym__end_of_file,
    STATE(31), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [508] = 5,
    ACTIONS(73), 1,
      sym__end_of_file_,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      sym__line_ending_,
    STATE(127), 1,
      sym__end_of_file,
    STATE(23), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [525] = 5,
    ACTIONS(73), 1,
      sym__end_of_file_,
    ACTIONS(77), 1,
      sym__line_ending_,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    STATE(129), 1,
      sym__end_of_file,
    STATE(31), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [542] = 5,
    ACTIONS(73), 1,
      sym__end_of_file_,
    ACTIONS(77), 1,
      sym__line_ending_,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    STATE(130), 1,
      sym__end_of_file,
    STATE(31), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [559] = 5,
    ACTIONS(73), 1,
      sym__end_of_file_,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
    ACTIONS(89), 1,
      sym__line_ending_,
    STATE(130), 1,
      sym__end_of_file,
    STATE(20), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [576] = 5,
    ACTIONS(73), 1,
      sym__end_of_file_,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
    ACTIONS(93), 1,
      sym__line_ending_,
    STATE(123), 1,
      sym__end_of_file,
    STATE(19), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [593] = 4,
    ACTIONS(95), 1,
      aux_sym__inline_value_token1,
    ACTIONS(97), 1,
      sym__line_ending_,
    STATE(94), 1,
      sym__line_ending,
    STATE(41), 2,
      sym__inline_value,
      sym__child_value,
  [607] = 4,
    ACTIONS(99), 1,
      aux_sym__inline_value_token1,
    ACTIONS(101), 1,
      sym__line_ending_,
    STATE(112), 1,
      sym__line_ending,
    STATE(139), 2,
      sym__inline_value,
      sym__child_value,
  [621] = 2,
    ACTIONS(105), 1,
      anon_sym_DOT,
    ACTIONS(103), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [631] = 2,
    ACTIONS(109), 1,
      anon_sym_DOT,
    ACTIONS(107), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [641] = 4,
    ACTIONS(111), 1,
      aux_sym__inline_value_token1,
    ACTIONS(113), 1,
      sym__line_ending_,
    STATE(85), 1,
      sym__line_ending,
    STATE(81), 2,
      sym__inline_value,
      sym__child_value,
  [655] = 3,
    ACTIONS(115), 1,
      sym__line_ending_,
    ACTIONS(53), 2,
      sym__end_of_file_,
      ts_builtin_sym_end,
    STATE(31), 2,
      sym__line_ending,
      aux_sym_src_repeat1,
  [667] = 2,
    ACTIONS(118), 1,
      anon_sym_DOT,
    ACTIONS(103), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [676] = 1,
    ACTIONS(120), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [683] = 1,
    ACTIONS(122), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [690] = 1,
    ACTIONS(124), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [697] = 1,
    ACTIONS(62), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [704] = 1,
    ACTIONS(126), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [711] = 1,
    ACTIONS(128), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [718] = 1,
    ACTIONS(130), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [725] = 1,
    ACTIONS(132), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [732] = 1,
    ACTIONS(134), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [739] = 1,
    ACTIONS(136), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [746] = 1,
    ACTIONS(138), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [753] = 1,
    ACTIONS(140), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [760] = 2,
    ACTIONS(142), 1,
      anon_sym_DOT,
    ACTIONS(107), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [769] = 2,
    ACTIONS(144), 1,
      anon_sym_DOT,
    ACTIONS(107), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [778] = 1,
    ACTIONS(146), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [785] = 2,
    ACTIONS(148), 1,
      anon_sym_DOT,
    ACTIONS(103), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [794] = 1,
    ACTIONS(107), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [801] = 1,
    ACTIONS(150), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [808] = 1,
    ACTIONS(103), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [815] = 1,
    ACTIONS(152), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [822] = 1,
    ACTIONS(154), 4,
      sym__name_,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [829] = 1,
    ACTIONS(120), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [835] = 1,
    ACTIONS(107), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [841] = 1,
    ACTIONS(138), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [847] = 1,
    ACTIONS(136), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [853] = 1,
    ACTIONS(138), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [859] = 1,
    ACTIONS(132), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [865] = 1,
    ACTIONS(124), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [871] = 1,
    ACTIONS(140), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [877] = 1,
    ACTIONS(126), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [883] = 1,
    ACTIONS(132), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [889] = 1,
    ACTIONS(136), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [895] = 1,
    ACTIONS(107), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [901] = 1,
    ACTIONS(103), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [907] = 1,
    ACTIONS(150), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [913] = 1,
    ACTIONS(140), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [919] = 1,
    ACTIONS(120), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [925] = 1,
    ACTIONS(103), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [931] = 1,
    ACTIONS(62), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [937] = 1,
    ACTIONS(130), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [943] = 1,
    ACTIONS(126), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [949] = 1,
    ACTIONS(154), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [955] = 1,
    ACTIONS(152), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [961] = 1,
    ACTIONS(122), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [967] = 1,
    ACTIONS(124), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [973] = 1,
    ACTIONS(128), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [979] = 1,
    ACTIONS(128), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [985] = 1,
    ACTIONS(122), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [991] = 1,
    ACTIONS(134), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [997] = 1,
    ACTIONS(150), 3,
      sym__line_ending_,
      sym__end_of_file_,
      ts_builtin_sym_end,
  [1003] = 1,
    ACTIONS(146), 3,
      sym__name_,
      sym__samedent_,
      sym__line_ending_,
  [1009] = 2,
    ACTIONS(156), 1,
      sym__end_of_file_,
    STATE(54), 1,
      sym__end_of_file,
  [1016] = 2,
    ACTIONS(158), 1,
      sym__indent_,
    STATE(3), 1,
      sym__increase_indent,
  [1023] = 2,
    ACTIONS(160), 1,
      sym__line_ending_,
    STATE(135), 1,
      sym__line_ending,
  [1030] = 2,
    ACTIONS(162), 1,
      aux_sym__integer_token1,
    STATE(137), 1,
      sym__integer,
  [1037] = 2,
    ACTIONS(164), 1,
      aux_sym__integer_token1,
    STATE(138), 1,
      sym__integer,
  [1044] = 2,
    ACTIONS(166), 1,
      aux_sym__integer_token1,
    STATE(78), 1,
      sym__integer,
  [1051] = 2,
    ACTIONS(168), 1,
      aux_sym__integer_token1,
    STATE(80), 1,
      sym__integer,
  [1058] = 2,
    ACTIONS(170), 1,
      sym__samedent_,
    STATE(36), 1,
      sym__current_indent,
  [1065] = 2,
    ACTIONS(15), 1,
      sym__end_of_file_,
    STATE(69), 1,
      sym__end_of_file,
  [1072] = 2,
    ACTIONS(15), 1,
      sym__end_of_file_,
    STATE(57), 1,
      sym__end_of_file,
  [1079] = 2,
    ACTIONS(172), 1,
      sym__indent_,
    STATE(4), 1,
      sym__increase_indent,
  [1086] = 2,
    ACTIONS(174), 1,
      sym__samedent_,
    STATE(71), 1,
      sym__current_indent,
  [1093] = 2,
    ACTIONS(176), 1,
      sym__end_of_file_,
    STATE(128), 1,
      sym__end_of_file,
  [1100] = 2,
    ACTIONS(176), 1,
      sym__end_of_file_,
    STATE(125), 1,
      sym__end_of_file,
  [1107] = 2,
    ACTIONS(178), 1,
      aux_sym__integer_token1,
    STATE(34), 1,
      sym__integer,
  [1114] = 2,
    ACTIONS(180), 1,
      aux_sym__integer_token1,
    STATE(38), 1,
      sym__integer,
  [1121] = 2,
    ACTIONS(182), 1,
      sym__line_ending_,
    STATE(75), 1,
      sym__line_ending,
  [1128] = 2,
    ACTIONS(184), 1,
      sym__end_of_file_,
    STATE(42), 1,
      sym__end_of_file,
  [1135] = 2,
    ACTIONS(184), 1,
      sym__end_of_file_,
    STATE(33), 1,
      sym__end_of_file,
  [1142] = 2,
    ACTIONS(156), 1,
      sym__end_of_file_,
    STATE(64), 1,
      sym__end_of_file,
  [1149] = 2,
    ACTIONS(107), 1,
      sym__samedent_,
    ACTIONS(186), 1,
      anon_sym_DOT,
  [1156] = 2,
    ACTIONS(103), 1,
      sym__samedent_,
    ACTIONS(188), 1,
      anon_sym_DOT,
  [1163] = 2,
    ACTIONS(103), 1,
      sym__line_ending_,
    ACTIONS(190), 1,
      anon_sym_DOT,
  [1170] = 2,
    ACTIONS(107), 1,
      sym__line_ending_,
    ACTIONS(192), 1,
      anon_sym_DOT,
  [1177] = 2,
    ACTIONS(194), 1,
      aux_sym__integer_token1,
    STATE(120), 1,
      sym__integer,
  [1184] = 2,
    ACTIONS(196), 1,
      aux_sym__integer_token1,
    STATE(122), 1,
      sym__integer,
  [1191] = 2,
    ACTIONS(198), 1,
      aux_sym__integer_token1,
    STATE(76), 1,
      sym__integer,
  [1198] = 2,
    ACTIONS(200), 1,
      aux_sym__integer_token1,
    STATE(79), 1,
      sym__integer,
  [1205] = 2,
    ACTIONS(202), 1,
      sym__indent_,
    STATE(5), 1,
      sym__increase_indent,
  [1212] = 2,
    ACTIONS(204), 1,
      sym__line_ending_,
    STATE(52), 1,
      sym__line_ending,
  [1219] = 1,
    ACTIONS(154), 1,
      sym__samedent_,
  [1223] = 1,
    ACTIONS(126), 1,
      sym__samedent_,
  [1227] = 1,
    ACTIONS(107), 1,
      sym__samedent_,
  [1231] = 1,
    ACTIONS(103), 1,
      sym__samedent_,
  [1235] = 1,
    ACTIONS(138), 1,
      sym__samedent_,
  [1239] = 1,
    ACTIONS(124), 1,
      sym__samedent_,
  [1243] = 1,
    ACTIONS(122), 1,
      sym__samedent_,
  [1247] = 1,
    ACTIONS(206), 1,
      sym_assignment_operator,
  [1251] = 1,
    ACTIONS(128), 1,
      sym__samedent_,
  [1255] = 1,
    ACTIONS(75), 1,
      ts_builtin_sym_end,
  [1259] = 1,
    ACTIONS(132), 1,
      sym__samedent_,
  [1263] = 1,
    ACTIONS(136), 1,
      sym__samedent_,
  [1267] = 1,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
  [1271] = 1,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
  [1275] = 1,
    ACTIONS(120), 1,
      sym__samedent_,
  [1279] = 1,
    ACTIONS(208), 1,
      ts_builtin_sym_end,
  [1283] = 1,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
  [1287] = 1,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
  [1291] = 1,
    ACTIONS(150), 1,
      sym__samedent_,
  [1295] = 1,
    ACTIONS(140), 1,
      sym__samedent_,
  [1299] = 1,
    ACTIONS(130), 1,
      sym__samedent_,
  [1303] = 1,
    ACTIONS(152), 1,
      sym__samedent_,
  [1307] = 1,
    ACTIONS(212), 1,
      sym_assignment_operator,
  [1311] = 1,
    ACTIONS(128), 1,
      sym__line_ending_,
  [1315] = 1,
    ACTIONS(122), 1,
      sym__line_ending_,
  [1319] = 1,
    ACTIONS(134), 1,
      sym__samedent_,
  [1323] = 1,
    ACTIONS(103), 1,
      sym__line_ending_,
  [1327] = 1,
    ACTIONS(107), 1,
      sym__line_ending_,
  [1331] = 1,
    ACTIONS(138), 1,
      sym__line_ending_,
  [1335] = 1,
    ACTIONS(146), 1,
      sym__samedent_,
  [1339] = 1,
    ACTIONS(124), 1,
      sym__line_ending_,
  [1343] = 1,
    ACTIONS(214), 1,
      sym_assignment_operator,
  [1347] = 1,
    ACTIONS(126), 1,
      sym__line_ending_,
  [1351] = 1,
    ACTIONS(132), 1,
      ts_builtin_sym_end,
  [1355] = 1,
    ACTIONS(216), 1,
      sym_assignment_operator,
  [1359] = 1,
    ACTIONS(218), 1,
      ts_builtin_sym_end,
  [1363] = 1,
    ACTIONS(220), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 53,
  [SMALL_STATE(5)] = 106,
  [SMALL_STATE(6)] = 161,
  [SMALL_STATE(7)] = 193,
  [SMALL_STATE(8)] = 225,
  [SMALL_STATE(9)] = 257,
  [SMALL_STATE(10)] = 279,
  [SMALL_STATE(11)] = 297,
  [SMALL_STATE(12)] = 321,
  [SMALL_STATE(13)] = 345,
  [SMALL_STATE(14)] = 370,
  [SMALL_STATE(15)] = 391,
  [SMALL_STATE(16)] = 412,
  [SMALL_STATE(17)] = 437,
  [SMALL_STATE(18)] = 457,
  [SMALL_STATE(19)] = 474,
  [SMALL_STATE(20)] = 491,
  [SMALL_STATE(21)] = 508,
  [SMALL_STATE(22)] = 525,
  [SMALL_STATE(23)] = 542,
  [SMALL_STATE(24)] = 559,
  [SMALL_STATE(25)] = 576,
  [SMALL_STATE(26)] = 593,
  [SMALL_STATE(27)] = 607,
  [SMALL_STATE(28)] = 621,
  [SMALL_STATE(29)] = 631,
  [SMALL_STATE(30)] = 641,
  [SMALL_STATE(31)] = 655,
  [SMALL_STATE(32)] = 667,
  [SMALL_STATE(33)] = 676,
  [SMALL_STATE(34)] = 683,
  [SMALL_STATE(35)] = 690,
  [SMALL_STATE(36)] = 697,
  [SMALL_STATE(37)] = 704,
  [SMALL_STATE(38)] = 711,
  [SMALL_STATE(39)] = 718,
  [SMALL_STATE(40)] = 725,
  [SMALL_STATE(41)] = 732,
  [SMALL_STATE(42)] = 739,
  [SMALL_STATE(43)] = 746,
  [SMALL_STATE(44)] = 753,
  [SMALL_STATE(45)] = 760,
  [SMALL_STATE(46)] = 769,
  [SMALL_STATE(47)] = 778,
  [SMALL_STATE(48)] = 785,
  [SMALL_STATE(49)] = 794,
  [SMALL_STATE(50)] = 801,
  [SMALL_STATE(51)] = 808,
  [SMALL_STATE(52)] = 815,
  [SMALL_STATE(53)] = 822,
  [SMALL_STATE(54)] = 829,
  [SMALL_STATE(55)] = 835,
  [SMALL_STATE(56)] = 841,
  [SMALL_STATE(57)] = 847,
  [SMALL_STATE(58)] = 853,
  [SMALL_STATE(59)] = 859,
  [SMALL_STATE(60)] = 865,
  [SMALL_STATE(61)] = 871,
  [SMALL_STATE(62)] = 877,
  [SMALL_STATE(63)] = 883,
  [SMALL_STATE(64)] = 889,
  [SMALL_STATE(65)] = 895,
  [SMALL_STATE(66)] = 901,
  [SMALL_STATE(67)] = 907,
  [SMALL_STATE(68)] = 913,
  [SMALL_STATE(69)] = 919,
  [SMALL_STATE(70)] = 925,
  [SMALL_STATE(71)] = 931,
  [SMALL_STATE(72)] = 937,
  [SMALL_STATE(73)] = 943,
  [SMALL_STATE(74)] = 949,
  [SMALL_STATE(75)] = 955,
  [SMALL_STATE(76)] = 961,
  [SMALL_STATE(77)] = 967,
  [SMALL_STATE(78)] = 973,
  [SMALL_STATE(79)] = 979,
  [SMALL_STATE(80)] = 985,
  [SMALL_STATE(81)] = 991,
  [SMALL_STATE(82)] = 997,
  [SMALL_STATE(83)] = 1003,
  [SMALL_STATE(84)] = 1009,
  [SMALL_STATE(85)] = 1016,
  [SMALL_STATE(86)] = 1023,
  [SMALL_STATE(87)] = 1030,
  [SMALL_STATE(88)] = 1037,
  [SMALL_STATE(89)] = 1044,
  [SMALL_STATE(90)] = 1051,
  [SMALL_STATE(91)] = 1058,
  [SMALL_STATE(92)] = 1065,
  [SMALL_STATE(93)] = 1072,
  [SMALL_STATE(94)] = 1079,
  [SMALL_STATE(95)] = 1086,
  [SMALL_STATE(96)] = 1093,
  [SMALL_STATE(97)] = 1100,
  [SMALL_STATE(98)] = 1107,
  [SMALL_STATE(99)] = 1114,
  [SMALL_STATE(100)] = 1121,
  [SMALL_STATE(101)] = 1128,
  [SMALL_STATE(102)] = 1135,
  [SMALL_STATE(103)] = 1142,
  [SMALL_STATE(104)] = 1149,
  [SMALL_STATE(105)] = 1156,
  [SMALL_STATE(106)] = 1163,
  [SMALL_STATE(107)] = 1170,
  [SMALL_STATE(108)] = 1177,
  [SMALL_STATE(109)] = 1184,
  [SMALL_STATE(110)] = 1191,
  [SMALL_STATE(111)] = 1198,
  [SMALL_STATE(112)] = 1205,
  [SMALL_STATE(113)] = 1212,
  [SMALL_STATE(114)] = 1219,
  [SMALL_STATE(115)] = 1223,
  [SMALL_STATE(116)] = 1227,
  [SMALL_STATE(117)] = 1231,
  [SMALL_STATE(118)] = 1235,
  [SMALL_STATE(119)] = 1239,
  [SMALL_STATE(120)] = 1243,
  [SMALL_STATE(121)] = 1247,
  [SMALL_STATE(122)] = 1251,
  [SMALL_STATE(123)] = 1255,
  [SMALL_STATE(124)] = 1259,
  [SMALL_STATE(125)] = 1263,
  [SMALL_STATE(126)] = 1267,
  [SMALL_STATE(127)] = 1271,
  [SMALL_STATE(128)] = 1275,
  [SMALL_STATE(129)] = 1279,
  [SMALL_STATE(130)] = 1283,
  [SMALL_STATE(131)] = 1287,
  [SMALL_STATE(132)] = 1291,
  [SMALL_STATE(133)] = 1295,
  [SMALL_STATE(134)] = 1299,
  [SMALL_STATE(135)] = 1303,
  [SMALL_STATE(136)] = 1307,
  [SMALL_STATE(137)] = 1311,
  [SMALL_STATE(138)] = 1315,
  [SMALL_STATE(139)] = 1319,
  [SMALL_STATE(140)] = 1323,
  [SMALL_STATE(141)] = 1327,
  [SMALL_STATE(142)] = 1331,
  [SMALL_STATE(143)] = 1335,
  [SMALL_STATE(144)] = 1339,
  [SMALL_STATE(145)] = 1343,
  [SMALL_STATE(146)] = 1347,
  [SMALL_STATE(147)] = 1351,
  [SMALL_STATE(148)] = 1355,
  [SMALL_STATE(149)] = 1359,
  [SMALL_STATE(150)] = 1363,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(136),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(146),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(144),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 2),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_src_repeat1, 2),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_src_repeat1, 2),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_src_repeat1, 2), SHIFT_REPEAT(10),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__multiline_map_repeat1, 2),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__multiline_map_repeat1, 2), SHIFT_REPEAT(136),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 1, .production_id = 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 3, .production_id = 3),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 3),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 1),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 2, .production_id = 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 2),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 2, .production_id = 3),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__signed_number, 1),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unsigned_number, 1),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_src_repeat1, 2), SHIFT_REPEAT(31),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 3),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__decimal, 3),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_text, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_empty, 1),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__signed_decimal, 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_literal, 1, .production_id = 5),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_of_file, 1),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map_named_entry, 3, .production_id = 4),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map, 4),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_number, 1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_empty, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__multiline_map_entry, 1, .production_id = 2),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inline_value, 3),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__child_value, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 3, .production_id = 1),
  [210] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_name, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 4),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_src, 4, .production_id = 3),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_strux_external_scanner_create(void);
void tree_sitter_strux_external_scanner_destroy(void *);
bool tree_sitter_strux_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_strux_external_scanner_serialize(void *, char *);
void tree_sitter_strux_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_strux(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_strux_external_scanner_create,
      tree_sitter_strux_external_scanner_destroy,
      tree_sitter_strux_external_scanner_scan,
      tree_sitter_strux_external_scanner_serialize,
      tree_sitter_strux_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
